/**
 * Semantic tile catalog for the default RPG Maker MZ **Dungeon** tileset
 * sheets (Dungeon_A1, Dungeon_A2, Dungeon_A4, Dungeon_A5, Dungeon_B, Dungeon_C), for Phase 4 (default-tileset catalogs). Names are RPG
 * Maker's own official English tile labels, taken verbatim from the tileset
 * image .txt sidecars that ship in the new-project template
 * (RPGMZ.app .../newdata/img/tilesets/*.txt) — so authoritative, not guessed.
 * Keyed by sheet **filename**; each array is indexed by *local index within the
 * sheet* (autotile kind for A1–A4, tile offset for the flat A5/B/C sheets).
 * Resolution to a real tile id happens in index.ts, which uses the sheet’s
 * *slot* in a project’s Tilesets.json (a slot, not the filename, fixes the id).
 *
 * Generated from the sidecars (see Session History); do not hand-edit — correct
 * the source .txt or the generator instead.
 */
export const DUNGEON_TILE_NAMES: Record<string, string[]> = {
  Dungeon_A1: [
    'Water A',
    'Deep Water',
    'Swamp Grass',
    'Lotus Pads (Flowers)',
    'Lava',
    'Waterfall A (Lava Cave)',
    'Water B (Grass Maze)',
    'Waterfall B (Grass Maze)',
    'Water C (Dirt Cave)',
    'Waterfall C (Dirt Cave)',
    'Water D (Rock Cave)',
    'Waterfall D (Rock Cave)',
    'Water E (Crystal)',
    'Waterfall E (Crystal)',
    'Canal',
    'Waterfall (Stone Wall)',
  ],
  Dungeon_A2: [
    'Ground A (Dirt Cave)',
    'Ground B (Grass Maze)',
    'Dark Ground A (Dirt Cave)',
    'Dark Ground B (Grass Maze)',
    'Hole A (Dirt Cave)',
    'Hole B (Grass Maze)',
    'Hole I (Stone Floor)',
    'Ground Cracks',
    'Ground C (Rock Cave)',
    'Ground D (Crystal)',
    'Dark Ground C (Rock Cave)',
    'Dark Ground D (Crystal)',
    'Hole C (Rock Cave)',
    'Hole D (Crystal)',
    'Hole J',
    'Soil on Ground',
    'Ground E (Lava Cave)',
    'Ground F (In Body)',
    'Dark Ground E (Lava Cave)',
    'Rug A',
    'Hole E (Lava Cave)',
    'Hole F (In Body)',
    'Fencepost',
    'Moss on Ground',
    'Ground G (Ice Cave)',
    'Ground H (Demonic World)',
    'Dark Ground G (Ice Cave)',
    'Rug B',
    'Hole G (Ice Cave)',
    'Hole H (Demonic World)',
    'Raised Stone',
    'Poison Swamp',
  ],
  Dungeon_A4: [
    'Wall A (Dirt Cave)',
    'Wall B (Rock Cave)',
    'Wall C (Lava Cave)',
    'Wall D (Ice Cave)',
    'Wall E (Grass Maze)',
    'Wall F (Crystal)',
    'Wall G (In Body)',
    'Wall H (Demonic World)',
    'Wall A (Dirt Cave)',
    'Wall B (Rock Cave)',
    'Wall C (Lava Cave)',
    'Wall D (Ice Cave)',
    'Wall E (Grass Maze)',
    'Wall F (Crystal)',
    'Wall G (In Body)',
    'Wall H (Demonic World)',
    'Wall I (Stone)',
    'Wall J (Brick)',
    'Wall K (Stone)',
    'Wall L (Marble)',
    'Wall M (Moss)',
    'Wall N (Castle)',
    'Wall O (Fort)',
    'Wall P (Demon Castle)',
    'Wall I (Stone)',
    'Wall J (Brick)',
    'Wall K (Stone)',
    'Wall L (Marble)',
    'Wall M (Moss)',
    'Wall N (Castle)',
    'Wall O (Fort)',
    'Wall P (Demon Castle)',
    'Wall Q (Mecha)',
    'Wall R (Stone)',
    'Wall S (Frozen)',
    'Wall T (Dirt Cave, Gold)',
    'Ledge A (Dirt Cave)',
    'Ledge B (Rock Cave)',
    'Ledge C (Lava Cave)',
    'Ledge D (Ice Cave)',
    'Wall Q (Mecha)',
    'Wall R (Stone)',
    'Wall S (Frozen)',
    'Wall T (Dirt Cave, Gold)',
    'Ledge A (Dirt Cave)',
    'Ledge B (Rock Cave)',
    'Ledge C (Lava Cave)',
    'Ledge D (Ice Cave)',
  ],
  Dungeon_A5: [
    'Darkness',
    'Floating Floor A (Dirt)',
    'Floating Floor B (Rock)',
    'Translucent Floor A',
    'Translucent Floor B',
    'Stairs A (Dirt)',
    'Stairs B (Translucent)',
    'Wire Mesh',
    'Transparent',
    'Floating Floor A (Dirt)',
    'Floating Floor B (Rock)',
    'Translucent Floor A',
    'Translucent Floor B',
    'Stairs A (Rock)',
    'Stairs B (Translucent)',
    'Wire Mesh',
    'Ground A (Wood)',
    'Ground B (Wood)',
    'Ground (Wood, Ruins)',
    'Ground (Wood, Ruins)',
    'Cobblestones A',
    'Cobblestones B',
    'Cobblestones C',
    'Cobblestones D',
    'Cobblestones E',
    'Decorative Tile A',
    'Decorative Tile B',
    'Interior Floor A',
    'Interior Floor B (Light)',
    'Tile Floor A',
    'Tile Floor B',
    'Tile Floor C',
    'Cobblestones F',
    'Ground C (Rock Cave, Red Crystal)',
    'Ground D (Rock Cave, Blue Crystal)',
    'Ground E (Rock Cave, Green Crystal)',
    'Ground F (Dirt)',
    'Ground G (Demon Castle)',
    'Ground H (Gold)',
    'Ground I (Ice)',
    'Stairs A (Dirt Cave, Left)',
    'Stairs A (Dirt Cave, Center)',
    'Stairs A (Dirt Cave, Right)',
    'Stairs A (Dirt Cave)',
    'Stairs B (Rock Cave, Left)',
    'Stairs B (Rock Cave, Center)',
    'Stairs B (Rock Cave, Right)',
    'Stairs B (Rock Cave)',
    'Stairs C (Lava Cave, Left)',
    'Stairs C (Lava Cave, Center)',
    'Stairs C (Lava Cave, Right)',
    'Stairs C (Lava Cave)',
    'Stairs D (Ice Cave, Left)',
    'Stairs D (Ice Cave, Center)',
    'Stairs D (Ice Cave, Right)',
    'Stairs D (Ice Cave)',
    'Stairs E (Grass Maze, Left)',
    'Stairs E (Grass Maze, Center)',
    'Stairs E (Grass Maze, Right)',
    'Stairs E (Grass Maze)',
    'Stairs F (Crystal, Left)',
    'Stairs F (Crystal, Center)',
    'Stairs F (Crystal, Right)',
    'Stairs F (Crystal)',
    'Stairs G (In Body, Left)',
    'Stairs G (In Body, Center)',
    'Stairs G (In Body, Right)',
    'Stairs G (In Body)',
    'Stairs H (Demonic World, Left)',
    'Stairs H (Demonic World, Center)',
    'Stairs H (Demonic World, Right)',
    'Stairs H (Demonic World)',
    'Stairs I (Stone, Left)',
    'Stairs I (Stone, Center)',
    'Stairs I (Stone, Right)',
    'Stairs I (Stone)',
    'Stairs J (Ruins, Left)',
    'Stairs J (Ruins, Center)',
    'Stairs J (Ruins, Right)',
    'Stairs J (Ruins)',
    'Stairs K (Stone, Left)',
    'Stairs K (Stone, Center)',
    'Stairs K (Stone, Right)',
    'Stairs K (Stone)',
    'Stairs L (Ruins, Left)',
    'Stairs L (Ruins, Center)',
    'Stairs L (Ruins, Right)',
    'Stairs L (Ruins)',
    'Ground (Dirt Cave, Ruins)',
    'Ground (Rock Cave, Ruins)',
    'Ground (Lava Cave, Ruins)',
    'Ground (Ice Cave, Ruins)',
    'Ground (Grass Maze, Ruins)',
    'Ground (Crystal, Ruins)',
    'Ground (In Body, Ruins)',
    'Ground (Demonic World, Ruins)',
    'Cobblestones A (Ruins)',
    'Cobblestones B (Ruins)',
    'Cobblestones C (Ruins)',
    'Cobblestones D (Ruins)',
    'Cobblestones E (Ruins)',
    'Decorative Tile A (Ruins)',
    'Decorative Tile B (Ruins)',
    'Interior Floor A (Ruins)',
    'Tile Floor A (Ruins)',
    'Tile Floor B (Ruins)',
    'Tile Floor C (Ruins)',
    'Cobblestones F (Ruins)',
    'Ground F (Dirt, Ruins)',
    'Ground G (Demon Castle, Ruins)',
    'Ground I (Ice, Ruins)',
    'Relief Floor Tile (Silver)',
    'Large Relief Floor Tile',
    'Large Relief Floor Tile',
    'Large Relief Floor Tile (Ruins)',
    'Large Relief Floor Tile (Ruins)',
    'Directional Floor Tile A (Down)',
    'Directional Floor Tile B (Up)',
    'Relief Floor Tile A (Gold)',
    'Relief Floor Tile B (Gold)',
    'Large Relief Floor Tile',
    'Large Relief Floor Tile',
    'Large Relief Floor Tile (Ruins)',
    'Large Relief Floor Tile (Ruins)',
    'Directional Floor Tile C (Left)',
    'Directional Floor Tile D (Right)',
    'Relief Floor Tile C (Gold)',
    'Relief Floor Tile D (Gold, Ruins)',
  ],
  Dungeon_B: [
    'Transparent',
    'Wall Moss',
    'Stairs A (Up)',
    'Stairs B (Up)',
    'Metal Ladder',
    'Wood Ladder',
    'Rope',
    'Vines A',
    'Fissures A',
    'Wall Fern',
    'Stairs A (Down)',
    'Stairs B (Down)',
    'Metal Ladder',
    'Wood Ladder',
    'Rope',
    'Vines A',
    'Crumbling Wall',
    'Dug-Up Ground',
    'Stairs C (Up)',
    'Stairs D (Up)',
    'Metal Ladder',
    'Wood Ladder',
    'Rope',
    'Vines B (Down)',
    'Crumbling Wall',
    'Dug-Up Ground',
    'Stairs C (Down)',
    'Stairs D (Down)',
    'Hole A (Metal Ladder)',
    'Hole B (Wood Ladder)',
    'Hole C (Rope)',
    'Hole D',
    'Gravel A (Dirt Cave)',
    'Gravel B (Rock Cave)',
    'Gravel C (Lava Cave)',
    'Ice Pieces ',
    'Small Sprouts A (Grass Maze)',
    'Small Crystals',
    'Detritus (In Body)',
    'Small Sprouts B (Demonic World)',
    'Boulder A (Dirt Cave)',
    'Boulder B (Rock Cave)',
    'Boulder C (Lava Cave)',
    'Lump of Ice',
    'Boulder D (Grass Maze)',
    'Crystal',
    'Spherical Lump',
    'Boulder E (Demonic World)',
    'Tall Rock A (Dirt Cave)',
    'Tall Rock B (Rock Cave)',
    'Tall Rock C (Lava Cave)',
    'Tall Lump of Ice',
    'Tall Rock D  (Grass Maze)',
    'Large Crystal',
    'Large Growth',
    'Tall Rock E (Demonic World)',
    'Tall Rock A (Dirt Cave)',
    'Tall Rock B (Rock Cave)',
    'Tall Rock C (Lava Cave)',
    'Tall Lump of Ice',
    'Tall Rock D  (Grass Maze)',
    'Large Crystal',
    'Large Growth',
    'Tall Rock E (Demonic World)',
    'Monument A',
    'Monument B',
    'Large Monument',
    'Large Monument',
    'Large Monument',
    'Large Monument (Light)',
    'Large Monument (Light)',
    'Large Monument (Light)',
    'Monument A',
    'Monument C',
    'Large Monument',
    'Large Monument',
    'Large Monument',
    'Large Monument (Light)',
    'Large Monument (Light)',
    'Large Monument (Light)',
    'Statue',
    'Angel Statue',
    'Goddess Statue',
    'Dais',
    'God Statue',
    'Demon Statue',
    'Dragon Statue',
    'Dragon Statue',
    'Statue',
    'Angel Statue',
    'Goddess Statue',
    'Broken Statue',
    'God Statue',
    'Demon Statue',
    'Dragon Statue',
    'Dragon Statue',
    'Obelisk',
    'Stone Pillar A',
    'Stone Pillar B',
    'Stone Pillar B (Moss)',
    'Stone Pillar B (Ice)',
    'Stone Pillar C',
    'Stone Pillar D',
    'Orb Pillar',
    'Obelisk',
    'Stone Pillar A',
    'Stone Pillar B',
    'Stone Pillar B (Moss)',
    'Stone Pillar B (Ice)',
    'Stone Pillar C',
    'Stone Pillar D',
    'Orb Pillar',
    'Obelisk',
    'Broken Stone Pillar A',
    'Broken Stone Pillar B',
    'Broken Stone Pillar B (Moss)',
    'Broken Stone Pillar B (Ice)',
    'Stone Pillar C',
    'Broken Stone Pillar D',
    'Broken Orb Pillar',
    'Rubble',
    'Rubble (Moss)',
    'Rubble (Ice)',
    'Broken Stone Pillar C',
    'Rubble (Dirt)',
    'Scrap Wood',
    'Barricade A (H)',
    'Barricade B (V)',
    'Wall Bracing',
    'Wall Bracing',
    'Wall Bracing',
    'Wall Bracing',
    'Wall Bracing',
    'Wall Bracing (Abandoned Mine)',
    'Wall Bracing (Abandoned Mine)',
    'Wall Bracing (Abandoned Mine)',
    'Wall Bracing',
    'Wall Bracing',
    'Wall Bracing',
    'Wall Bracing',
    'Wall Bracing',
    'Wall Bracing (Abandoned Mine)',
    'Wall Bracing (Abandoned Mine)',
    'Wall Bracing (Abandoned Mine)',
    'Log Bridge (V)',
    'Log Bridge (H)',
    'Wood Bridge (V)',
    'Wood Bridge (H)',
    'Stone Bridge (V)',
    'Stone Bridge (H)',
    'Wood Bridge (V)',
    'Wood Bridge (H)',
    'Bridge Spar (Wood, Center A)',
    'Bridge Spar (Wood, Left)',
    'Bridge Spar (Wood, Center B)',
    'Bridge Spar (Wood, Right)',
    'Bridge Spar (Stone, Center A)',
    'Bridge Spar (Stone, Left)',
    'Bridge Spar (Stone, Center B)',
    'Bridge Spar (Stone, Right)',
    'Exit A',
    'Entrance A',
    'Exit B',
    'Entrance B',
    'Exit C',
    'Entrance C',
    'Window A',
    'Window B',
    'Exit D',
    'Entrance D',
    'Exit E',
    'Entrance E',
    'Light From Exit A (Top)',
    'Light From Exit B (Bottom)',
    'Window A',
    'Window B',
    'Spider Web',
    'Stone Tablet',
    'Stone Tablet (Ruins)',
    'Entrance A',
    'Entrance A (Extend)',
    'Entrance A (Top Half A)',
    'Entrance B',
    'Entrance A (Top Half B)',
    'Wall Vines A',
    'Wall Vines B',
    'Wall Vines C',
    'Fissures B',
    'Fissures C',
    'Fissures D',
    'Fissures E',
    'Beanstalk A',
    'Wall Vines A',
    'Wall Vines B',
    'Wall Vines C',
    'Fissures B',
    'Fissures C',
    'Fissures D',
    'Beanstalk B (Snow)',
    'Beanstalk C (Dead)',
    'Large Gravel Mound A (Dirt)',
    'Large Gravel Mound A (Dirt)',
    'Large Gravel Mound B (Stone)',
    'Large Gravel Mound B (Stone)',
    'Large Gold Mound',
    'Large Gold Mound',
    'Large Silver Mound',
    'Large Silver Mound',
    'Large Gravel Mound A (Dirt)',
    'Large Gravel Mound A (Dirt)',
    'Large Gravel Mound B (Stone)',
    'Large Gravel Mound B (Stone)',
    'Large Gold Mound',
    'Large Gold Mound',
    'Large Silver Mound',
    'Large Silver Mound',
    'Gravel Mound (Dirt)',
    'Gravel Mound (Stone)',
    'Gold Bricks A',
    'Gold Bricks B',
    'Crate A (Dirt)',
    'Crate B (Stone)',
    'Crate C (Ruins)',
    'Pot A (Ruins)',
    'Gold Mound',
    'Silver Mound',
    'Silver Bricks A',
    'Silver Bricks B',
    'Crate D (Gold Dust)',
    'Crate E (Silver Dust)',
    'Pot A',
    'Pot B',
    'Shovel',
    'Pickax',
    'Rope',
    'Mound of Gold Coins',
    'Crate F',
    'Crate G',
    'Barrel A',
    'Barrel B (Ruins)',
    'Large Bones',
    'Large Bones',
    'Bones A',
    'Table (Ruins)',
    'Jail Bars',
    'Jail Bars',
    'Jail Bars',
    'Jail Bars',
    'Large Bones',
    'Large Bones',
    'Bones B',
    'Stool (Ruins)',
    'Jail Bars',
    'Jail Bars',
    'Jail Bars',
    'Jail Bars',
  ],
  Dungeon_C: [
    'Decorative Pillar A (Stone)',
    'Decorative Pillar B (Stone)',
    'Decorative Pillar C (Temple)',
    'Decorative Pillar D (Rock Cave)',
    'Decorative Pillar E (Demon Castle)',
    'Decorative Pillar F (Fort)',
    'Decorative Pillar G (Dirt Cave)',
    'Decorative Pillar H (Factory)',
    'Decorative Pillar A (Stone)',
    'Decorative Pillar B (Stone)',
    'Decorative Pillar C (Temple)',
    'Decorative Pillar D (Rock Cave)',
    'Decorative Pillar E (Demon Castle)',
    'Decorative Pillar F (Fort)',
    'Decorative Pillar G (Dirt Cave)',
    'Decorative Pillar H (Factory)',
    'Decorative Pillar A (Stone)',
    'Decorative Pillar B (Stone)',
    'Decorative Pillar C (Temple)',
    'Decorative Pillar D (Rock Cave)',
    'Decorative Pillar E (Demon Castle)',
    'Decorative Pillar F (Fort)',
    'Decorative Pillar G (Dirt Cave)',
    'Decorative Pillar H (Factory)',
    'Decorative Pillar A (Stone, Ruins)',
    'Decorative Pillar B (Stone, Ruins)',
    'Decorative Pillar C (Temple, Ruins)',
    'Decorative Pillar D (Rock Cave, Ruins)',
    'Decorative Pillar E (Demon Castle, Ruins)',
    'Decorative Pillar F (Fort, Ruins)',
    'Decorative Pillar G (Dirt Cave, Ruins)',
    'Decorative Pillar A (Stone, Front, Ruins)',
    'Decorative Pillar A (Stone, Ruins)',
    'Decorative Pillar B (Stone, Ruins)',
    'Decorative Pillar C (Temple, Ruins)',
    'Decorative Pillar D (Rock Cave, Ruins)',
    'Decorative Pillar E (Demon Castle, Ruins)',
    'Decorative Pillar F (Fort, Ruins)',
    'Decorative Pillar G (Dirt Cave, Ruins)',
    'Decorative Pillar D (Rock Cave, Front, Ruins)',
    'Decorative Pillar A (Stone, Ruins)',
    'Decorative Pillar B (Stone, Ruins)',
    'Decorative Pillar C (Temple, Ruins)',
    'Decorative Pillar D (Rock Cave, Ruins)',
    'Decorative Pillar E (Demon Castle, Ruins)',
    'Decorative Pillar F (Fort, Ruins)',
    'Decorative Pillar G (Dirt Cave, Ruins)',
    'Decorative Pillar F (Fort, Front, Ruins)',
    'Decorative Pillar A (Stone, Front)',
    'Decorative Pillar B (Stone, Front)',
    'Decorative Pillar C (Temple, Front)',
    'Decorative Pillar D (Rock Cave, Front)',
    'Decorative Pillar E (Demon Castle, Front)',
    'Decorative Pillar F (Fort, Front)',
    'Decorative Pillar G (Dirt Cave, Front)',
    'Decorative Pillar H (Factory, Front)',
    'Gate A',
    'Gate A',
    'Gate A',
    'Gate B',
    'Gate B',
    'Gate B',
    'Decorative Pillar I (Demonic)',
    'Decorative Pillar I (Demonic, Ruins)',
    'Gate A',
    'Gate A',
    'Gate A',
    'Gate B',
    'Gate B',
    'Gate B',
    'Decorative Pillar I (Demonic)',
    'Decorative Pillar I (Demonic, Ruins)',
    'Gate A',
    'Gate A',
    'Gate A',
    'Gate B',
    'Gate B',
    'Gate B',
    'Coffin A (Right)',
    'Coffin A (Right)',
    'Hexagram',
    'Hexagram',
    'Hexagram',
    'Hexagram (Lit)',
    'Hexagram (Lit)',
    'Hexagram (Lit)',
    'Coffin B (Top)',
    'Coffin C (Bottom)',
    'Hexagram',
    'Hexagram',
    'Hexagram',
    'Hexagram (Lit)',
    'Hexagram (Lit)',
    'Hexagram (Lit)',
    'Coffin B (Top)',
    'Coffin C (Bottom)',
    'Hexagram',
    'Hexagram',
    'Hexagram',
    'Hexagram (Lit)',
    'Hexagram (Lit)',
    'Hexagram (Lit)',
    'Coffin D  (Left)',
    'Coffin D  (Left)',
    'Rails',
    'Rails',
    'Rails',
    'Rails',
    'Rails (Ruins)',
    'Rails (Ruins)',
    'Rails (Ruins)',
    'Rails (Ruins)',
    'Rails',
    'Railroad Ties A',
    'Rails',
    'Rails',
    'Rails',
    'Rails',
    'Rails',
    'Rails',
    'Rails',
    'Railroad Ties B',
    'Rails',
    'Rails',
    'Rails',
    'Rails',
    'Rails',
    'Rails',
    'Mural A',
    'Hieroglyph',
    'Hieroglyph',
    'Large Mural A',
    'Large Mural A',
    'Large Mural A',
    'Bed',
    'Bed (Ruins)',
    'Mural B',
    'Hieroglyph',
    'Hieroglyph',
    'Large Mural B',
    'Large Mural B',
    'Large Mural B',
    'Bed',
    'Bed (Ruins)',
    'Middle Window A',
    'Middle Window B',
    'Middle Window C',
    'Middle Window D (Ruins)',
    'Window (Demon Castle)',
    'Table',
    'Cheap Bed',
    'Straw Bed',
    'Middle Window A',
    'Middle Window B',
    'Middle Window C',
    'Middle Window D (Ruins)',
    'Window (Demon Castle)',
    'Stool',
    'Cheap Bed',
    'Straw Bed',
    'Large Window A',
    'Large Window B',
    'Large Window C',
    'Stained Glass Window',
    'Large Window D',
    'Window A',
    'Window B',
    'Window C',
    'Large Window A',
    'Large Window B',
    'Large Window C',
    'Stained Glass Window',
    'Large Window D',
    'Window A',
    'Window B',
    'Window C',
    'Chest A',
    'Cabinet',
    'Closet',
    'Chest of Drawers',
    'Dish Cabinet',
    'Wine Rack',
    'Bottle Shelf A',
    'Bottle Shelf B',
    'Chest B',
    'Chest C',
    'Closet',
    'Chest of Drawers',
    'Dish Cabinet',
    'Wine Rack',
    'Bottle Shelf A',
    'Bottle Shelf B',
    'Tipped Shelf',
    'Sundries Shelf A',
    'Sundries Shelf A',
    'Sundries Shelf B',
    'Medicine Shelf',
    'Bookshelf A',
    'Bookshelf B',
    'Bookshelf B',
    'Tipped Shelf',
    'Sundries Shelf A',
    'Sundries Shelf A',
    'Sundries Shelf B',
    'Medicine Shelf',
    'Bookshelf A',
    'Bookshelf B',
    'Bookshelf B',
    'Curtains A',
    'Curtains B',
    'Curtains C',
    'Curtains D',
    'Curtains A (Ruins)',
    'Curtains B (Ruins)',
    'Curtains C (Ruins)',
    'Curtains D (Ruins)',
    'Curtains A',
    'Curtains B',
    'Curtains C',
    'Curtains D',
    'Curtains A (Ruins)',
    'Curtains B (Ruins)',
    'Curtains C (Ruins)',
    'Curtains D (Ruins)',
    'Clock',
    'Mirror',
    'Clock (Ruins)',
    'Mirror (Ruins)',
    'Stacked Crates',
    'Stacked Crates',
    'Tapestry A',
    'Tapestry  A (Ruins)',
    'Clock',
    'Mirror',
    'Clock (Ruins)',
    'Mirror (Ruins)',
    'Stacked Crates',
    'Stacked Crates',
    'Tapestry A',
    'Tapestry  A (Ruins)',
    'Chair A (Wood)',
    'Chair B (Stone)',
    'Throne A',
    'Throne A',
    'Throne A',
    'Throne B (Demon Castle)',
    'Throne B (Demon Castle)',
    'Throne B (Demon Castle)',
    'Chair A (Wood)',
    'Chair B (Stone)',
    'Throne A',
    'Throne A',
    'Throne A',
    'Throne B (Demon Castle)',
    'Throne B (Demon Castle)',
    'Throne B (Demon Castle)',
  ],
};
