/**
 * Semantic tile catalog for the default RPG Maker MZ **Inside** tileset
 * sheets (Inside_A1, Inside_A2, Inside_A4, Inside_A5, Inside_B, Inside_C), for Phase 4 (default-tileset catalogs). Names are RPG
 * Maker's own official English tile labels, taken verbatim from the tileset
 * image .txt sidecars that ship in the new-project template
 * (RPGMZ.app .../newdata/img/tilesets/*.txt) — so authoritative, not guessed.
 * Keyed by sheet **filename**; each array is indexed by *local index within the
 * sheet* (autotile kind for A1–A4, tile offset for the flat A5/B/C sheets).
 * Resolution to a real tile id happens in index.ts, which uses the sheet’s
 * *slot* in a project’s Tilesets.json (a slot, not the filename, fixes the id).
 *
 * Generated from the sidecars (see Session History); do not hand-edit — correct
 * the source .txt or the generator instead.
 */
export const INSIDE_TILE_NAMES: Record<string, string[]> = {
  Inside_A1: [
    'Water A',
    'Deep Water',
    'Lotus Pads (Flowers)',
    'Purple Water',
    'Water B (Surround Stonewall)',
    'Waterfall A (Shine Fall)',
    'Pond A (Rock Pond)',
    'Waterfall B (Grid Fall)',
    'Water C (Tile)',
    'Water D (Small Hole)',
    'Water E (Water Surface)',
    'Water F (Water Footing)',
    'Water G (Surround Waterwall)',
    'Water H (Big Hole)',
    'Pond B (Purple Rock Pond)',
    'Waterfall C (Purple Fall)',
  ],
  Inside_A2: [
    'Ground A (Wood Floor Stripe)',
    'Ground B (Stone Floor Tile)',
    'Ground C (Dirt Floor)',
    'Tatami',
    'Hole A (Orange Cave)',
    'Raised Stone A (Blue)',
    'Ground D (Black Floor)',
    'Table A (Wood)',
    'Ground E (Wood Floor Border)',
    'Ground F (Stone Floor Brick)',
    'Rug A (Red Flower)',
    'Rug B (Oriental Green)',
    'Hole B (Brown Cave)',
    'Raised Stone B (Purple)',
    'Ground G (Dark Enclave Floor)',
    'Table B (Dark Wood)',
    'Ground H (Wood Floor Lattice)',
    'Ground I (Stone Floor Color Tile)',
    'Rug C (Oriental Blue)',
    'Rug D (Oriental Redpink)',
    'Hole C (Black Cave)',
    'Raised Stone B (Yellow)',
    'Ground J (Enclave Floor)',
    'Table C (White Wood)',
    'Ground K (Oriental Floor)',
    'Ground L (Stone Floor X Tile)',
    'Rug E (Oriental Red)',
    'Rug F (Oriental Purple)',
    'Hole D (Square Black Cave)',
    'Raised Stone C (Gray)',
    'Ground M (Stone Enclave Floor)',
    'Table D (White Cloth)',
  ],
  Inside_A4: [
    'Wall A (Stone)',
    'Wall B (Castle)',
    'Wall C (Fort)',
    'Wall D (Stone)',
    'Wall E (Stone)',
    'Wall F (Brick)',
    'Wall G (Stone)',
    'Interior Wall A (Stone)',
    'Wall A (Stone)',
    'Wall B (Castle)',
    'Wall C (Fort)',
    'Wall D (Stone)',
    'Wall E (Stone)',
    'Wall F (Brick)',
    'Wall G (Stone)',
    'Interior Wall A (Stone)',
    'Wall H (Wood)',
    'Wall I (Log)',
    'Wall J (Wood)',
    'Interior Wall B (Plaster)',
    'Interior Wall C (Plaster)',
    'Wall K (Stone)',
    'Wall L (Marble)',
    'Wall M (Marble)',
    'Wall H (Wood)',
    'Wall I (Log)',
    'Wall J (Wood)',
    'Interior Wall B (Plaster)',
    'Interior Wall C (Plaster)',
    'Wall K (Stone)',
    'Wall L (Marble)',
    'Wall M (Marble)',
    'Interior Wall D (Desert)',
    'Interior Wall E (Desert)',
    'Interior Wall F (Mansion)',
    'Interior Wall G (Mansion)',
    'Wall N (Tent)',
    'Wall O (Demon Castle)',
    'Wall P (Gold)',
    'Wall Q (Ice)',
    'Interior Wall D (Desert)',
    'Interior Wall E (Desert)',
    'Interior Wall F (Mansion)',
    'Interior Wall G (Mansion)',
    'Wall N (Tent)',
    'Wall O (Demon Castle)',
    'Wall P (Gold)',
    'Wall Q (Ice)',
  ],
  Inside_A5: [
    'Darkness',
    'Dirt Floor',
    'Stone Bridge (V, Left)',
    'Stone Bridge (V Center)',
    'Stone Bridge (V, Riight)',
    'Stone Bridge (H, Top)',
    'Stone Bridge (H Center)',
    'Broken Bridge (H, Top)',
    'Transparent',
    'Dirt Ledge',
    'Broken Bridge (V, Left)',
    'Broken Bridge (V Center)',
    'Broken Bridge (V, Riight)',
    'Stone Bridge (H, Bottom)',
    'Broken Bridge (H Center)',
    'Broken Bridge (H, Bottom)',
    'Wood Floor A',
    'Wood Floor B',
    'Wood Floor C',
    'Wood Floor D',
    'Cobblestones A',
    'Cobblestones B',
    'Cobblestones C',
    'Cobblestones D',
    'Ledge A (Wood)',
    'Ledge B (Wood)',
    'Ledge C (Wood)',
    'Ledge D (Wood)',
    'Ledge E (Stone)',
    'Ledge F (Stone)',
    'Ledge G (Stone)',
    'Ledge H (Stone)',
    'Wood Floor A (Ruins)',
    'Wood Floor B (Ruins)',
    'Wood Floor C (Ruins)',
    'Wood Floor D (Ruins)',
    'Cobblestones A (Ruins)',
    'Cobblestones B (Ruins)',
    'Cobblestones C (Ruins)',
    'Cobblestones D (Ruins)',
    'Cobblestones E',
    'Interior Floor A (Tile)',
    'Interior Floor B (Tile)',
    'Interior Floor C (Tile)',
    'Interior Floor D (Stone)',
    'Interior Floor E (Tile)',
    'Interior Floor F (Tile)',
    'Interior Floor G (Tile)',
    'Ledge I (Stone)',
    'Ledge J (Stone)',
    'Ledge K (Stone)',
    'Ledge L (Stone)',
    'Ledge M (Stone)',
    'Ledge N (Stone)',
    'Ledge O (Stone)',
    'Ledge P (Stone)',
    'Cobblestones E (Ruins)',
    'Interior Floor A (Tile, Ruins)',
    'Interior Floor B (Tile, Ruins)',
    'Interior Floor C (Tile, Ruins)',
    'Interior Floor D (Stone, Ruins)',
    'Interior Floor E (Tile, Ruins)',
    'Interior Floor F (Tile, Ruins)',
    'Interior Floor G (Tile, Ruins)',
    'Cobblestones F',
    'Interior Floor H (Dirt)',
    'Interior Floor I (Marble)',
    'Interior Floor J (Carpet)',
    'Interior Floor K (Demon Castle)',
    'Interior Floor L (Demon Castle)',
    'Gold Floor',
    'Ice Floor',
    'Ledge Q (Stone)',
    'Ledge R (Dirt)',
    'Ledge S (Marble)',
    'Ledge T (Carpet)',
    'Ledge U (Demon Castle)',
    'Ledge V (Demon Castle)',
    'Ledge W (Gold)',
    'Ledge X (Ice)',
    'Cobblestones F (Ruins)',
    'Interior Floor H (Dirt, Ruins)',
    'Interior Floor I (Marble, Ruins)',
    'Interior Floor J (Carpet, Ruins)',
    'Interior Floor K (Demon Castle, Ruins)',
    'Interior Floor L (Demon Castle, Ruins)',
    'Gold Floor (Ruins)',
    'Ice Floor (Ruins)',
    'Stairs A (Wood, Left)',
    'Stairs A (Wood, Center)',
    'Stairs A (Wood)',
    'Stairs A (Wood)',
    'Stairs B (Stone, Left)',
    'Stairs B (Stone, Center)',
    'Stairs B (Stone, Right)',
    'Stairs B (Stone)',
    'Stairs C (Stone, Left)',
    'Stairs C (Stone, Center)',
    'Stairs C (Stone, Right)',
    'Stairs C (Stone)',
    'Stairs C (Stone, Ruins, Left)',
    'Stairs C (Stone, Ruins, Center)',
    'Stairs C (Stone, Ruins, Right)',
    'Stairs C (Stone, Ruins)',
    'Stairs D (Carpet, Left)',
    'Stairs D (Carpet, Center)',
    'Stairs D (Carpet, Right)',
    'Stairs D (Carpet)',
    'Stairs E (Carpet, Left)',
    'Stairs E (Carpet, Center)',
    'Stairs E (Carpet, Right)',
    'Stairs E (Carpet)',
    'Large Relief Floor Tile',
    'Large Relief Floor Tile',
    'Large Relief Floor Tile (Ruins)',
    'Large Relief Floor Tile (Ruins)',
    'Relief Floor Tile A (Silver)',
    'Relief Floor Tile B (Silver)',
    'Relief Floor Tile C (Gold)',
    'Relief Floor Tile D (Gold)',
    'Large Relief Floor Tile',
    'Large Relief Floor Tile',
    'Large Relief Floor Tile (Ruins)',
    'Large Relief Floor Tile (Ruins)',
    'Relief Floor Tile E (Silver, Ruins)',
    'Relief Floor Tile F (Silver)',
    'Relief Floor Tile G (Gold, Ruins)',
    'Relief Floor Tile H (Gold)',
  ],
  Inside_B: [
    'Transparent',
    'Stairs A (Up)',
    'Stairs B (Up)',
    'Stairs C (Up)',
    'Stairs D (Up)',
    'Metal Ladder',
    'Wood Ladder',
    'Rope',
    'Hole',
    'Stairs A (Down)',
    'Stairs B (Down)',
    'Stairs C (Down)',
    'Stairs D (Down)',
    'Metal Ladder',
    'Wood Ladder',
    'Rope',
    'Entrance A',
    'Entrance A (Extend)',
    'Entrance A (Top Half A)',
    'Entrance B',
    'Entrance A (Top Half B)',
    'Metal Ladder',
    'Wood Ladder',
    'Rope',
    'Stone Pillar A',
    'Stone Pillar B',
    'Fort Pillar',
    'Rubble',
    'Rubble',
    'Hole A (Metal Ladder)',
    'Hole B (Wood Ladder)',
    'Hole C (Rope)',
    'Stone Pillar A',
    'Stone Pillar B',
    'Fort Pillar',
    'Stone Tablet',
    'Fissures A',
    'Fissures B',
    'Fissures C',
    'Fissures D',
    'Broken Stone Pillar A',
    'Broken Stone Pillar B',
    'Broken Fort Pillar',
    'Stone Tablet (Ruins)',
    'Fissures A',
    'Fissures B',
    'Fissures C',
    'Fissures E',
    'Curtains A',
    'Curtains B',
    'Curtains C',
    'Curtains D',
    'Curtains A (Ruins)',
    'Curtains B (Ruins)',
    'Curtains C (Ruins)',
    'Curtains D (Ruins)',
    'Curtains A',
    'Curtains B',
    'Curtains C',
    'Curtains D',
    'Curtains A (Ruins)',
    'Curtains B (Ruins)',
    'Curtains C (Ruins)',
    'Curtains D (Ruins)',
    'Middle Window A',
    'Middle Window A',
    'Middle Window B',
    'Middle Window B',
    'Large Window A',
    'Large Window B',
    'Large Window C',
    'Stained Glass Window',
    'Middle Window A',
    'Middle Window A',
    'Middle Window B',
    'Middle Window B',
    'Large Window A',
    'Large Window B',
    'Large Window C',
    'Stained Glass Window',
    'Tapestry A',
    'Tapestry A (Ruins)',
    'Swords A',
    'Swords B',
    'Large Window D',
    'Window A',
    'Window B',
    'Window C',
    'Tapestry A',
    'Tapestry A (Ruins)',
    'Shield',
    'Posted Notice',
    'Large Window D',
    'Window A',
    'Window B',
    'Window C',
    'Sofa (Castle)',
    'Sofa (Castle)',
    'Sofa (Castle)',
    'Sofa (Castle)',
    'Sofa (Castle)',
    'Chair A (Wood)',
    'Chair B (Stone)',
    'Throne (Demon Castle)',
    'Sofa (Castle)',
    'Sofa (Castle)',
    'Sofa (Castle)',
    'Sofa (Castle)',
    'Sofa (Castle)',
    'Chair A (Wood)',
    'Chair B (Stone)',
    'Throne (Demon Castle)',
    'Table A',
    'Table A',
    'Table B',
    'Table C',
    'Table D',
    'Clock',
    'Mirror',
    'Window (Demon Castle)',
    'Stool A',
    'Stool B',
    'Stool C',
    'Table E',
    'Table F',
    'Clock',
    'Mirror',
    'Window (Demon Castle)',
    'World Map',
    'World Map',
    'Painting',
    'Painting',
    'Portrait A',
    'Portrait B',
    'Painting A',
    'Painting B',
    'Chest A',
    'Cabinet',
    'Closet',
    'Chest of Drawers',
    'Dish Cabinet',
    'Wine Rack',
    'Bottle Shelf A',
    'Bottle Shelf B',
    'Chest B',
    'Chest C',
    'Closet',
    'Chest of Drawers',
    'Dish Cabinet',
    'Wine Rack',
    'Bottle Shelf A',
    'Bottle Shelf B',
    'Bread Shelf',
    'Sundries Shelf A',
    'Sundries Shelf A',
    'Sundries Shelf B',
    'Medicine Shelf',
    'Bookshelf A',
    'Bookshelf B',
    'Bookshelf B',
    'Bread Shelf',
    'Sundries Shelf A',
    'Sundries Shelf A',
    'Sundries Shelf B',
    'Medicine Shelf',
    'Bookshelf A',
    'Bookshelf B',
    'Bookshelf B',
    'Bed',
    'Large Bed',
    'Large Bed',
    'Cheap Bed A',
    'Cheap Bed B',
    'Straw Bed',
    'Bed (Ruins)',
    'Tipped Shelf',
    'Bed',
    'Large Bed',
    'Large Bed',
    'Cheap Bed A',
    'Cheap Bed B',
    'Straw Bed',
    'Bed (Ruins)',
    'Tipped Shelf',
    'Simple Shelf A (Jars)',
    'Simple Shelf B (Books)',
    'Fireplace A (Stone)',
    'Fireplace B (Brick)',
    'Fireplace C (Iron)',
    'Large Fireplace',
    'Large Fireplace',
    'Large Fireplace',
    'Simple Shelf C (Sacks)',
    'Simple Shelf D (Bottles)',
    'Fireplace A (Stone)',
    'Fireplace B (Brick)',
    'Fireplace C (Iron)',
    'Large Fireplace',
    'Large Fireplace',
    'Large Fireplace',
    'Oven',
    'Sink',
    'Kitchen Counter A',
    'Kitchen Counter B',
    'Dresser',
    'Piano',
    'Piano',
    'Piano',
    'Simple Shelf E',
    'Pot A',
    'Pot B',
    'Basin',
    'Barrel',
    'Piano',
    'Piano',
    'Piano',
    'Posted Notice (Ruins)',
    'Basin',
    'Tub A',
    'Tub B',
    'Scrap Wood',
    'Pipe Organ',
    'Pipe Organ',
    'Pipe Organ',
    'Crate A',
    'Crate B',
    'Stacked Crates',
    'Stacked Crates',
    'Crate C (Ruins)',
    'Pipe Organ',
    'Pipe Organ',
    'Pipe Organ',
    'Crate D',
    'Crate E',
    'Stacked Crates',
    'Stacked Crates',
    'Pot C (Ruins)',
    'Barrel (Ruins)',
    'Table A (Ruins)',
    'Stool (Ruins)',
    'Crate F',
    'Crate G',
    'Sacks C',
    'Large Crate',
    'Jail Bar',
    'Jail Bar',
    'Jail Bar',
    'Jail Bar',
    'Sack A',
    'Sack B',
    'Sacks C',
    'Large Crate',
    'Jail Bar',
    'Jail Bar',
    'Jail Bar',
    'Jail Bar',
  ],
  Inside_C: [
    'Teapot A',
    'Teapot B',
    'Cup (Lower Left)',
    'Cup (Upper Right)',
    'Pot A',
    'Pot B',
    'Glass A (Lower Left)',
    'Glass A (Upper Right)',
    'Bottle A',
    'Bottle B',
    'Glass B (Lower Left)',
    'Glass B (Upper Right)',
    'Glass C (Lower Left)',
    'Glass C (Upper Right)',
    'Glass D (Lower Left)',
    'Glass D (Upper Right)',
    'Pot C',
    'Pot D',
    'Pint Mug A (Lower Left)',
    'Pint Mug A (Upper Right)',
    'Pint Mug B (Lower Left)',
    'Pint Mug B (Upper Right)',
    'Glass E (Lower Left)',
    'Glass E (Upper Right)',
    'Bottle C',
    'Broken Bottle',
    'Bottle D',
    'Bottle E',
    'Bottle F',
    'Pint Mug C',
    'Pint Mug D',
    'Glass F',
    'Side Dishes',
    'Meal (Meat)',
    'Assorted Vegetables',
    'Assorted Fruitsl',
    'Roast Chicken',
    'Meal (Fish)',
    'Pasta',
    'Assorted Cakes',
    'Dinner Set A (Bottom)',
    'Dinner Set B (Top)',
    'Dinner Set C (Left)',
    'Dinner Set D (Right)',
    'Gratin',
    'Fried Rice',
    'Beef Stew',
    'Paella',
    'Breakfast Set A (Bottom)',
    'Breakfast Set B (Top)',
    'Breakfast Set C (Left)',
    'Breakfast Set D (Right)',
    'Assorted Cheeses',
    'Stew',
    'Mushroom Dishes',
    'Tart',
    'Beer Barrel A',
    'Beer Barrel B',
    'Plate A',
    'Plates B',
    'Plates C',
    'Chopping Board',
    'Soup Bowl',
    'Paella Pan',
    'Closed Book A (V)',
    'Closed Book A (H)',
    'Closed Book B (V)',
    'Closed Book B (H)',
    'Open Book A (V)',
    'Open Book A (H)',
    'Closed Books C',
    'Closed Book D',
    'Note A (V)',
    'Note A (H)',
    'Notes B (V)',
    'Pen A',
    'Map A (V)',
    'Map B (H)',
    'Note C (V)',
    'Note C (H)',
    'Notes D',
    'Envelope',
    'Scrolls A',
    'Scrolls B',
    'Planter A',
    'Planter B',
    'Potted Plant A',
    'Potted Plant B',
    'Case A',
    'Case B',
    'Case C',
    'Hourglass',
    'Small Box A',
    'Small Box B',
    'Small Box C',
    'Small Box D',
    'Sack A',
    'Sacks B',
    'Medicine Bottle A',
    'Medicine Bottles B',
    'Potion A',
    'Potion B',
    'Potion C',
    'Potion D',
    'Basket A',
    'Basket B',
    'Basket C',
    'Basket D',
    'Rugs A',
    'Rugs B',
    'Rugs C',
    'Balance',
    'Stuffed Doll A',
    'Stuffed Doll B',
    'Stuffed Doll C',
    'Doll A',
    'Doll B',
    'Doll C',
    'Gifts A',
    'Gifts B',
    'Globe',
    'Bell',
    'Cloth (Magic Circle)',
    'Crystal Ball',
    'Jewelry Case A',
    'Necklace',
    'Crown',
    'Jewelry Case B',
    'Sword A',
    'Swords B',
    'Swords C',
    'Axes',
    'Spears A',
    'Spears B',
    'Whip',
    'Knives',
    'Cooking Utensils',
    'Hanging Meat',
    'Shield A',
    'Shield B',
    "Men's Clothing A (Hanging)",
    "Men's Clothing B (Hanging)",
    "Women's Clothing A (Hanging)",
    "Women's Clothing B (Hanging)",
    'Sword Rack A',
    'Sword Rack B',
    'Hammers',
    'Bows & Arrows',
    "Blacksmith's Table A",
    "Blacksmith's Table B",
    'Large Basin',
    'Scrap Metal',
    'Helmet A',
    'Helmet B',
    'Helmet C',
    'Hat A (Stand)',
    'Hat B (Stand)',
    'Hat C (Stand)',
    "Women's Clothing A (Stand)",
    "Women's Clothing B (Stand)",
    'Armor A (Stand)',
    'Armor B (Stand)',
    'Armor C (Stand)',
    'Armor D (Stand)',
    "Women's Clothing C (Stand)",
    "Men's Clothing A (Stand)",
    "Men's Clothing B (Stand)",
    "Women's Clothing D (Stand)",
    'Church Symbol',
    'Goddess Statue',
    'God Statue',
    'Statue A',
    'Statue B',
    'Dais',
    'Repository of Swords',
    'Repository of Spears',
    'Church Symbol',
    'Goddess Statue',
    'God Statue',
    'Statue A',
    'Statue B',
    'Broken Statue',
    'Repository of Swords',
    'Repository of Spears',
    'Church Table',
    'Church Table',
    'Church Table',
    'Decorative Pillar A',
    'Decorative Pillar A',
    'Decorative Pillar B',
    'Decorative Pillar A (Ruins)',
    'Decorative Pillar B (Ruins)',
    'Church Table',
    'Church Table',
    'Church Table',
    'Decorative Pillar A (Ruins)',
    'Decorative Pillar A',
    'Decorative Pillar B',
    'Decorative Pillar A (Ruins)',
    'Decorative Pillar B (Ruins)',
    'Gold Bricks A',
    'Gold Bricks B',
    'Silver Bricks A',
    'Silver Bricks B',
    'Decorative Pillar A',
    'Decorative Pillar B',
    'Decorative Pillar A (Ruins)',
    'Decorative Pillar B (Ruins)',
    'Monument A',
    'Monument B',
    'Demon Statue',
    'Dragon Statue',
    'Dragon Statue',
    'Large Monument',
    'Large Monument',
    'Large Monument',
    'Monument A',
    'Monument C',
    'Demon Statue',
    'Dragon Statue',
    'Dragon Statue',
    'Large Monument',
    'Large Monument',
    'Large Monument',
    'Railings (Wood)',
    'Railings (Wood)',
    'Railings (Wood)',
    'Railings (Wood)',
    'Railings (Wood)',
    'Railings (Wood)',
    'Railings (Wood)',
    'Railings (Wood)',
    'Banister A (Wood)',
    'Banister A (Wood)',
    'Banister B (Stone)',
    'Banister B (Stone)',
    'Banister C (Temple)',
    'Banister C (Temple)',
    'Banister D (Castle)',
    'Banister D (Castle)',
    'Banister A (Wood)',
    'Banister A (Wood)',
    'Banister B (Stone)',
    'Banister B (Stone)',
    'Banister C (Temple)',
    'Banister C (Temple)',
    'Banister D (Castle)',
    'Banister D (Castle)',
    'Banister A (Wood)',
    'Banister A (Wood)',
    'Banister B (Stone)',
    'Banister B (Stone)',
    'Banister C (Temple)',
    'Banister C (Temple)',
    'Banister D (Castle)',
    'Banister D (Castle)',
  ],
};
