/**
 * Semantic tile catalog for the default RPG Maker MZ **Outside** tileset
 * sheets (Outside_A1, Outside_A2, Outside_A3, Outside_A4, Outside_A5, Outside_B, Outside_C), for Phase 4 (default-tileset catalogs). Names are RPG
 * Maker's own official English tile labels, taken verbatim from the tileset
 * image .txt sidecars that ship in the new-project template
 * (RPGMZ.app .../newdata/img/tilesets/*.txt) — so authoritative, not guessed.
 * Keyed by sheet **filename**; each array is indexed by *local index within the
 * sheet* (autotile kind for A1–A4, tile offset for the flat A5/B/C sheets).
 * Resolution to a real tile id happens in index.ts, which uses the sheet’s
 * *slot* in a project’s Tilesets.json (a slot, not the filename, fixes the id).
 *
 * Generated from the sidecars (see Session History); do not hand-edit — correct
 * the source .txt or the generator instead.
 */
export const OUTSIDE_TILE_NAMES: Record<string, string[]> = {
  Outside_A1: [
    'Water A (Meadow)',
    'Pond',
    'Swamp Grass A',
    'Swamp Grass B',
    'Water B (Snow)',
    'Waterfall A',
    'Canal',
    'Waterfall B (Stone Wall)',
    'Water C (Dirt)',
    'Waterfall C (Cliff)',
    'Water D (Sand)',
    'Waterfall D (Boulder)',
    'Water E (Port)',
    'Water Bubbles',
    'Poison Swamp',
    'Dead Tree',
  ],
  Outside_A2: [
    'Meadow',
    'Dirt (Meadow)',
    'Road (Meadow)',
    'Cobblestones A',
    'Bush',
    'Road Edging',
    'Fencepost A (Wood)',
    'Fissures',
    'Dirt',
    'Grass (Dirt)',
    'Road (Dirt)',
    'Cobblestones A (Dirt)',
    'Bush (Dead)',
    'Road Edging (Snow)',
    'Fencepost B (Metal)',
    'Soil',
    'Sand',
    'Grass (Sand)',
    'Road (Sand)',
    'Cobblestones B',
    'Bush (Sand)',
    'Hole',
    'Fencepost C (Stone)',
    'Moss',
    'Snow',
    'Dirt (Snow)',
    'Road (Snow)',
    'Carpet',
    'Bush (Snow)',
    'Hole',
    'Fencepost A (Wood, Snow)',
    'Ledge',
  ],
  Outside_A3: [
    'Roof A (Dressed Tile)',
    'Roof B (Pink Tile)',
    'Roof C (Orange Tile)',
    'Roof D (Yellow Tile)',
    'Roof E (Wood)',
    'Roof F (Wood, Ruins)',
    'Roof G (Log)',
    'Roof H (Dark Blue Tile)',
    'Outer Wall A (Rock Wall)',
    'Outer Wall B (Plaster)',
    'Outer Wall C (Brick)',
    'Outer Wall D (Plaster)',
    'Outer Wall E (Wood)',
    'Outer Wall F (Wood)',
    'Outer Wall G (Log)',
    'Outer Wall H (Demon Castle)外壁H（魔王城）\r',
    'Roof I (Green Tile)',
    'Roof J (Temple)',
    'Roof K (Stone)',
    'Roof L (Thatched)',
    'Roof M (Tent)',
    'Snow Roof A',
    'Snow Roof B',
    'Ice Roof',
    'Outer Wall I (Rock Wall)',
    'Outer Wall J (Temple)',
    'Outer Wall K (Rock Wall)',
    'Outer Wall L (Moss)',
    'Outer Wall M (Tent)',
    'Snow Outer Wall (Brick)',
    'Snow Outer Wall (Wood)',
    'Ice Outer Wall',
  ],
  Outside_A4: [
    'Wall A (Stone)',
    'Wall B (Stone)',
    'Wall C (Stone)',
    'Building A (Castle)',
    'Building B (Castle, Snow)',
    'Building C (Fort)',
    'Building D (Fort, Snow)',
    'Demon Castle',
    'Wall A (Stone)',
    'Wall B (Stone)',
    'Wall C (Stone)',
    'Building A (Castle)',
    'Building B (Castle, Snow)',
    'Building C (Fort)',
    'Building D (Fort, Snow)',
    'Demon Castle',
    'Wall C (Brick)',
    'Wall D (Stone)',
    'Wall E (Marble)',
    'Wall F (Marble)',
    'Building E (Dirt Wall)',
    'Building F (Desert)',
    'Wall G (Gold)',
    'Building G (Mecha)',
    'Wall C (Brick)',
    'Wall D (Stone)',
    'Wall E (Marble)',
    'Wall F (Marble)',
    'Building E (Dirt Wall)',
    'Building F (Desert)',
    'Wall G (Gold)',
    'Building G (Mecha)',
    'Wall H (Moss)',
    'Wall I (Hedge)',
    'Forest A',
    'Forest B (Snow)',
    'Ledge A (Meadow)',
    'Ledge B (Dirt)',
    'Ledge C (Desert)',
    'Ledge D (Snow)',
    'Wall H (Moss)',
    'Wall I (Hedge)',
    'Forest A',
    'Forest B (Snow)',
    'Ledge A (Meadow)',
    'Ledge B (Dirt)',
    'Ledge C (Desert)',
    'Ledge D (Snow)',
  ],
  Outside_A5: [
    'Darkness',
    'Night Sky A',
    'Large Bridge (H, Top)',
    'Large Bridge (H, Center)',
    'Large Bridge (Snow, H, Top)',
    'Large Bridge (V, Left)',
    'Large Bridge (V, Center)',
    'Large Bridge (V, Right)',
    'Transparent',
    'Night Sky B',
    'Large Bridge (H, Bottom)',
    'Large Bridge (Snow, H, Center)',
    'Large Bridge (Snow, H, Bottom)',
    'Large Bridge (Snow, V, Left)',
    'Large Bridge (Snow, V, Center)',
    'Large Bridge (Snow, V, Right)',
    'Meadow A',
    'Dirt A',
    'Desert A',
    'Snow A',
    'Meadow',
    'Dirt B',
    'Desert B',
    'Snow B',
    'Cobblestones A',
    'Cobblestones B',
    'Cobblestones C',
    'Cobblestones D',
    'Cobblestones A (Ruins)',
    'Cobblestones B (Ruins)',
    'Cobblestones C (Ruins)',
    'Cobblestones D (Ruins)',
    'Cobblestones E',
    'Cobblestones F',
    'Cobblestones G',
    'Demon Castle Floor',
    'Cobblestones E (Ruins)',
    'Cobblestones F (Ruins)',
    'Cobblestones G (Ruins)',
    'Demon Castle Floor (Ruins)',
    'Ledge (Port, Left)',
    'Ledge (Port, Center)',
    'Ledge (Port, Right)',
    'Ledge (Port)',
    'Tile Floor A',
    'Tile Floor B',
    'Tile Floor C (Gold)',
    'Tile Floor D (Ice)',
    'Stairs (Meadow, Left)',
    'Stairs (Meadow, Center)',
    'Stairs (Meadow, Right)',
    'Stairs (Meadow)',
    'Stairs (Dirt, Left)',
    'Stairs (Dirt, Center)',
    'Stairs (Dirt, Right)',
    'Stairs (Dirt)',
    'Stairs (Desert, Left)',
    'Stairs (Desert, Center)',
    'Stairs (Desert, Right)',
    'Stairs (Desert)',
    'Stairs (Snow, Left)',
    'Stairs (Snow, Center)',
    'Stairs (Snow, Right)',
    'Stairs (Snow)',
    'Stairs (Paved, Left)',
    'Stairs (Paved, Center)',
    'Stairs (Paved, Right)',
    'Stairs (Paved)',
    'Stairs (Ruins, Left)',
    'Stairs (Ruins, Center)',
    'Stairs (Ruins, Right)',
    'Stairs (Ruins)',
    'Large Relief Floor Tile',
    'Large Relief Floor Tile',
    'Large Relief Floor Tile (Ruins)',
    'Large Relief Floor Tile (Ruins)',
    'Farm Field A (Top)',
    'Farm Field A (Center)',
    'Farm Field B (Snow, Top)',
    'Farm Field B (Snow, Center)',
    'Large Relief Floor Tile',
    'Large Relief Floor Tile',
    'Large Relief Floor Tile (Ruins)',
    'Large Relief Floor Tile (Ruins)',
    'Farm Field A (Top)',
    'Farm Field A (Center)',
    'Farm Field B (Snow, Top)',
    'Farm Field B (Snow, Center)',
    'Ledge (Meadow)',
    'Ledge (Meadow)',
    'Ledge (Meadow)',
    'Garden A',
    'Garden B (Snow)',
    'Ledge (Dirt)',
    'Ledge (Dirt)',
    'Ledge (Dirt)',
    'Ledge (Meadow)',
    'Ledge (Meadow)',
    'Ledge (Meadow)',
    'Ledge (Meadow)',
    'Ledge (Meadow)',
    'Ledge (Dirt)',
    'Ledge (Dirt)',
    'Ledge (Dirt)',
    'Ledge (Meadow)',
    'Ledge (Meadow)',
    'Ledge (Meadow)',
    'Ledge (Meadow)',
    'Ledge (Meadow)',
    'Ledge (Dirt)',
    'Ledge (Dirt)',
    'Ledge (Dirt)',
    'Cliff',
    'Cliff',
    'Cliff',
    'Ledge (Dirt)',
    'Ledge (Dirt)',
    'Cliff',
    'Cliff',
    'Cliff',
    'Cliff (Meadow)',
    'Cliff (Meadow)',
    'Cliff (Meadow)',
    'Ledge (Dirt)',
    'Ledge (Dirt)',
    'Cliff (Dirt)',
    'Cliff (Dirt)',
    'Cliff (Dirt)',
  ],
  Outside_B: [
    'Transparent',
    'Stairs A (Up)',
    'Stairs B (Up)',
    'Stairs C (Up)',
    'Stairs D (Up)',
    'Tent A',
    'Tent A',
    'Tent A',
    'Streetlight A',
    'Stairs A (Down)',
    'Stairs B (Down)',
    'Stairs C (Down)',
    'Stairs D (Down)',
    'Tent A',
    'Tent A',
    'Tent A',
    'Streetlight A',
    'Metal Ladder',
    'Wood Ladder',
    'Rope',
    'Vines A',
    'Tent A',
    'Tent A (Entrance)',
    'Tent A',
    'Streetlight A',
    'Metal Ladder',
    'Wood Ladder',
    'Rope',
    'Vines A',
    'Tent B',
    'Tent B',
    'Tent B',
    'Streetlight B (Snow)',
    'Metal Ladder',
    'Wood Ladder',
    'Rope',
    'Vines B (Down)',
    'Tent B',
    'Tent B',
    'Tent B',
    'Streetlight B (Snow)',
    'Hole A (Metal Ladder)',
    'Hole B (Wood Ladder)',
    'Hole C (Rope)',
    'Hole D',
    'Tent B',
    'Tent B (Entrance, Snow)',
    'Tent B',
    'Streetlight B (Snow)',
    'Wall Vines A',
    'Wall Vines B',
    'Wall Vines C',
    'Fissures A',
    'Fissures B',
    'Fissures C',
    'Fissures D',
    'Wall Moss',
    'Wall Vines A',
    'Wall Vines B',
    'Wall Vines C',
    'Fissures A',
    'Fissures B',
    'Fissures C',
    'Fissures E',
    'Wall Fern',
    'Shop Sign (Sword)',
    'Shop Sign (Sword & Shield)',
    'Shop Sign (Armor)',
    'Shop Sign (Sack)',
    'Shop Sign (Teapot)',
    'Shop Sign (Inn)',
    'Shop Sign (Pub)',
    'Shop Sign (Eatery)',
    'Shop Sign (Hexagram)',
    'Shop Sign (Staves)',
    'Shop Sign (Coin)',
    'Shop Sign (Necklace)',
    'Shop Sign (Hammer)',
    'Shop Sign (Crest)',
    'Shop Sign (Blank)',
    'Log Bridge (V)',
    'Log Bridge (H)',
    'Wood Bridge (V)',
    'Wood Bridge (H)',
    'Stone Bridge (V)',
    'Stone Bridge (H)',
    'Wood Bridge (V)',
    'Wood Bridge (H)',
    'Bridge Spar (Wood, Center A)',
    'Bridge Spar (Wood, Left)',
    'Bridge Spar (Wood, Center B)',
    'Bridge Spar (Wood, Right)',
    'Bridge Spar (Stone, Center A)',
    'Bridge Spar (Stone, Left)',
    'Bridge Spar (Stone, Center B)',
    'Bridge Spar (Stone, Right)',
    'Window A',
    'Window B',
    'Window C',
    'Window D',
    'Middle Window A',
    'Middle Window B',
    'Middle Window C',
    'Middle Window D',
    'Window E',
    'Window F',
    'Window G',
    'Window H',
    'Middle Window A',
    'Middle Window E',
    'Middle Window C',
    'Middle Window D',
    'Large Window A',
    'Large Window B',
    'Large Window C',
    'Stained Glass Window',
    'Large Window D',
    'Middle Window F',
    'Middle Window G',
    'Middle Window H',
    'Large Window A',
    'Large Window E',
    'Large Window C',
    'Stained Glass Window B',
    'Large Window D',
    'Middle Window F',
    'Middle Window G',
    'Middle Window H',
    'Chimney',
    'Mooring Bollard A',
    'Mooring Bollard B (Rope)',
    'Entrance A',
    'Entrance A (Extend)',
    'Entrance A (Top Half A)',
    'Entrance B',
    'Entrance A (Top Half B)',
    'Chimney',
    'Sign A',
    'Sign B',
    'Well',
    'Stepping Stones',
    'Barrel',
    'Grave A',
    'Grave B',
    'Pot',
    'Basin A',
    'Basin B',
    'Rock Fire Pit A',
    'Rock Fire Pit B',
    'Barricade (H)',
    'Barricade (V)',
    'Beanstalk',
    'Grass A',
    'Grass B',
    'Grass C',
    'Grass D',
    'Stump',
    'Tree',
    'Tree',
    'Boulder A',
    'Flowers A',
    'Flowers B',
    'Flowers C',
    'Flowers D',
    'Fallen Log',
    'Tree',
    'Bush',
    'Boulder B',
    'Scarecrow',
    'Hole',
    'Firewood',
    'Rocks',
    'Crops A',
    'Crops B',
    'Crops C',
    'Crops D',
    'Large Tree',
    'Large Tree',
    'Large Tree',
    'Large Tree',
    'Large Crate',
    'Crate A',
    'Crate B',
    'Crate C',
    'Large Tree',
    'Large Tree',
    'Large Tree',
    'Large Tree',
    'Large Crate',
    'Crate D',
    'Crate E',
    'Crate F',
    'Conifer Tree (Snow)',
    'Conifer Tree (Snow)',
    'Conifer Tree (Snow)',
    'Conifer Tree (Snow)',
    'Scarecrow (Snow)',
    'Pot (Snow)',
    'Bucket (Snow)',
    'Crate (Snow)',
    'Large Conifer Tree (Snow)',
    'Large Conifer Tree (Snow)',
    'Large Conifer Tree (Snow)',
    'Large Conifer Tree (Snow)',
    'Mooring Bollard (Snow)',
    'Barricade (H, Snow)',
    'Barricade (H, Snow)',
    'Beanstalk (Snow)',
    'Stump (Snow)',
    'Sign A (Snow)',
    'Sign B (Snow)',
    'Well (Snow)',
    'Stepping Stones (Snow)',
    'Barrel (Snow)',
    'Grave A (Snow)',
    'Grave B (Snow)',
    'Snowman',
    'Grass A (Snow)',
    'Grass B (Snow)',
    'Grass C (Snow)',
    'Grass D (Snow)',
    'Conifer Tree (Snow)',
    'Conifer Tree (Snow)',
    'Boulder A (Snow)',
    'Dead Beanstalk',
    'Hole (Snow)',
    'Firewood (Snow)',
    'Rocks (Snow)',
    'Fallen Log (Snow)',
    'Conifer Tree (Snow)',
    'Bush (Snow)',
    'Boulder B (Snow)',
    'Dead Tree',
    'Dead Tree',
    'Mushrooms A',
    'Mushrooms B',
    'Palm Tree',
    'Palm Tree',
    'Cactus',
    'Dead Grass A',
    'Dead Tree',
    'Dead Tree (Shrub)',
    'Rafflesia',
    'Stump (Moss)',
    'Palm Tree',
    'Bush (Flowers)',
    'Fern',
    'Dead Grass B',
    'Hay',
    'Hay (Snow)',
    'Floral Patch',
    'Susuki Grass',
    'Fallen Leaves',
    'Lotus Pads A',
    'Lotus Pads B (Flowers)',
    'Lotus Pads C',
  ],
  Outside_C: [
    'Obelisk',
    'Stone Pillar A',
    'Stone Pillar B',
    'Stone Pillar B (Moss)',
    'Stone Pillar B (Snow)',
    'Stone Pillar C',
    'Stone Pillar D',
    'Demon Castle Pillar',
    'Obelisk',
    'Stone Pillar A',
    'Stone Pillar B',
    'Stone Pillar B (Moss)',
    'Stone Pillar B (Snow)',
    'Stone Pillar C',
    'Stone Pillar D',
    'Demon Castle Pillar',
    'Obelisk',
    'Broken Stone Pillar A',
    'Broken Stone Pillar B',
    'Broken Stone Pillar B (Moss)',
    'Broken Stone Pillar B (Snow)',
    'Broken Stone Pillar C',
    'Broken Stone Pillar D',
    'Broken Demon Castle Pillar',
    'Bones A',
    'Bones B',
    'Rubble',
    'Rubble B (Moss)',
    'Rubble C (Snow)',
    'Rubble D',
    'Rubble E',
    'Rubble F (Demon Castle)',
    'Monument A',
    'Monument B',
    'Large Monument',
    'Large Monument',
    'Large Monument',
    'Large Monument',
    'Large Monument',
    'Large Monument',
    'Monument A',
    'Monument C',
    'Large Monument',
    'Large Monument',
    'Large Monument',
    'Large Monument',
    'Large Monument',
    'Large Monument',
    'Monument A (Snow)',
    'Monument B (Snow)',
    'Large Monument (Snow)',
    'Large Monument (Snow)',
    'Large Monument (Snow)',
    'Large Monument (Snow)',
    'Large Monument (Snow)',
    'Large Monument (Snow)',
    'Monument A (Snow)',
    'Monument C (Snow)',
    'Large Monument (Snow)',
    'Large Monument (Snow)',
    'Large Monument (Snow)',
    'Large Monument (Snow)',
    'Large Monument (Snow)',
    'Large Monument (Snow)',
    'Statue A',
    'Statue B',
    'Angel Statue',
    'Demon Statue',
    'Dais',
    'Dragon Statue',
    'Dragon Statue',
    'God Statue',
    'Statue A',
    'Statue B',
    'Angel Statue',
    'Demon Statue',
    'Broken Dais',
    'Dragon Statue',
    'Dragon Statue',
    'God Statue',
    'Statue A (Snow)',
    'Statue B (Snow)',
    'Angel Statue (Snow)',
    'Demon Statue (Snow)',
    'Dais (Snow)',
    'Dragon Statue (Snow)',
    'Dragon Statue (Snow)',
    'Ice Statue',
    'Statue A (Snow)',
    'Statue B (Snow)',
    'Angel Statue (Snow)',
    'Demon Statue (Snow)',
    'Broken Dais (Snow)',
    'Dragon Statue (Snow)',
    'Dragon Statue (Snow)',
    'Ice Statue',
    'Tapestry A',
    'Tapestry A (Ruins)',
    'Tapestry B',
    'Tapestry B (Ruins)',
    'Tapestry C',
    'Tapestry C (Ruins)',
    'Tapestry D',
    'Tapestry D (Ruins)',
    'Tapestry A',
    'Tapestry A (Ruins)',
    'Tapestry B',
    'Tapestry B (Ruins)',
    'Tapestry C',
    'Tapestry C (Ruins)',
    'Tapestry D',
    'Tapestry D (Ruins)',
    'Window A (Demon Castle)',
    'Window B (Demon Castle)',
    'Window C (Demon Castle)',
    'Antenna',
    'Chimney',
    'Chimney',
    'Cave Entrance',
    'Mine Entrance',
    'Window A (Demon Castle)',
    'Window B (Demon Castle)',
    'Window D (Demon Castle)',
    'Antenna',
    'Chimney',
    'Chimney',
    'Cave Entrance',
    'Mine Entrance',
    'Roof A (Green Tile)',
    'Roof A (Green Tile)',
    'Roof A (Green Tile)',
    'Roof A (Green Tile)',
    'Roof A (Green Tile)',
    'Roof B (Snow)',
    'Roof B (Snow)',
    'Roof B (Snow)',
    'Roof A (Green Tile)',
    'Roof A (Green Tile)',
    'Roof A (Green Tile)',
    'Roof A (Green Tile)',
    'Roof A (Green Tile)',
    'Roof B (Snow)',
    'Roof B (Snow)',
    'Roof B (Snow)',
    'Roof A (Green Tile)',
    'Roof A (Green Tile)',
    'Roof A (Green Tile)',
    'Roof B (Snow)',
    'Roof B (Snow)',
    'Roof B (Snow)',
    'Roof B (Snow)',
    'Roof B (Snow)',
    'Roof C (Yellow Tile)',
    'Roof C (Yellow Tile)',
    'Roof C (Yellow Tile)',
    'Roof B (Snow)',
    'Roof B (Snow)',
    'Roof D (Wood)',
    'Roof D (Wood)',
    'Roof D (Wood)',
    'Roof C (Yellow Tile)',
    'Roof C (Yellow Tile)',
    'Roof C (Yellow Tile)',
    'Roof C (Yellow Tile)',
    'Roof C (Yellow Tile)',
    'Roof D (Wood)',
    'Roof D (Wood)',
    'Roof D (Wood)',
    'Roof C (Yellow Tile)',
    'Roof C (Yellow Tile)',
    'Roof C (Yellow Tile)',
    'Roof C (Yellow Tile)',
    'Roof C (Yellow Tile)',
    'Roof D (Wood)',
    'Roof D (Wood)',
    'Roof D (Wood)',
    'Round Tower A (Castle)',
    'Round Tower A (Castle)',
    'Round Tower B (Fort)',
    'Round Tower B (Fort)',
    'Roof Detail A (Green Tile)',
    'Roof Detail B (Snow)',
    'Roof D (Wood)',
    'Roof D (Wood)',
    'Round Tower A (Castle)',
    'Round Tower A (Castle)',
    'Round Tower B (Fort)',
    'Round Tower B (Fort)',
    'Roof Detail C (Yellow Tile)',
    'Roof Detail D (Wood)',
    'Roof D (Wood)',
    'Roof D (Wood)',
    'Round Tower A (Castle)',
    'Round Tower A (Castle)',
    'Round Tower B (Fort)',
    'Round Tower B (Fort)',
    "Round Tower A (Castle's Spire)",
    "Round Tower A (Castle's Spire)",
    'Round Tower B (Fort)',
    'Round Tower B (Fort)',
    'Round Tower A (Castle)',
    'Round Tower A (Castle)',
    'Round Tower B (Fort)',
    'Round Tower B (Fort)',
    "Round Tower A (Castle's Spire)",
    "Round Tower A (Castle's Spire)",
    'Round Tower B (Fort, Snow)',
    'Round Tower B (Fort, Snow)',
    'Round Tower A (Castle)',
    'Round Tower A (Castle)',
    'Round Tower B (Fort)',
    'Round Tower B (Fort)',
    "Round Tower A (Castle's Spire)",
    "Round Tower A (Castle's Spire)",
    'Round Tower C (Demon Castle)',
    'Round Tower C (Demon Castle)',
    'Round Tower A (Castle, Snow)',
    'Round Tower A (Castle, Snow)',
    'Round Tower B (Fort, Snow)',
    'Round Tower B (Fort, Snow)',
    'Round Tower A (Castle)',
    'Round Tower A (Castle)',
    'Round Tower C (Demon Castle)',
    'Round Tower C (Demon Castle)',
    'Round Tower A (Castle, Snow)',
    'Round Tower A (Castle, Snow)',
    'Round Tower B (Fort, Snow)',
    'Round Tower B (Fort, Snow)',
    "Round Tower A (Castle's Spire, Snow)",
    "Round Tower A (Castle's Spire, Snow)",
    'Round Tower C (Demon Castle)',
    'Round Tower C (Demon Castle)',
    'Round Tower A (Castle, Snow)',
    'Round Tower A (Castle, Snow)',
    'Round Tower B (Fort, Snow)',
    'Round Tower B (Fort, Snow)',
    "Round Tower A (Castle's Spire, Snow)",
    "Round Tower A (Castle's Spire, Snow)",
    'Round Tower C (Demon Castle)',
    'Round Tower C (Demon Castle)',
    'Round Tower A (Castle, Snow)',
    'Round Tower A (Castle, Snow)',
    'Round Tower B (Fort, Snow)',
    'Round Tower B (Fort, Snow)',
    "Round Tower A (Castle's Spire, Snow)",
    "Round Tower A (Castle's Spire, Snow)",
    'Round Tower C (Demon Castle)',
    'Round Tower C (Demon Castle)',
    'Round Tower A (Castle, Snow)',
    'Round Tower A (Castle, Snow)',
    'Round Tower B (Fort, Snow)',
    'Round Tower B (Fort, Snow)',
    'Round Tower A (Castle, Snow)',
    'Round Tower A (Castle, Snow)',
    'Round Tower C (Demon Castle)',
    'Round Tower C (Demon Castle)',
  ],
};
