/**
 * Semantic tile catalog for the default RPG Maker MZ **SF (Sci-Fi)** tileset
 * sheets (SF_Outside_A3, SF_Outside_A4, SF_Outside_A5, SF_Outside_B, SF_Outside_C, SF_Inside_A4, SF_Inside_B, SF_Inside_C), for Phase 4 (default-tileset catalogs). Names are RPG
 * Maker's own official English tile labels, taken verbatim from the tileset
 * image .txt sidecars that ship in the new-project template
 * (RPGMZ.app .../newdata/img/tilesets/*.txt) — so authoritative, not guessed.
 * Keyed by sheet **filename**; each array is indexed by *local index within the
 * sheet* (autotile kind for A1–A4, tile offset for the flat A5/B/C sheets).
 * Resolution to a real tile id happens in index.ts, which uses the sheet’s
 * *slot* in a project’s Tilesets.json (a slot, not the filename, fixes the id).
 *
 * Generated from the sidecars (see Session History); do not hand-edit — correct
 * the source .txt or the generator instead.
 */
export const SF_TILE_NAMES: Record<string, string[]> = {
  SF_Outside_A3: [
    'Roof A (Brick)',
    'Roof B (Factory)',
    'Roof C (Metal, Red Rust)',
    'Roof D (Barracks)',
    'Roof E (Barracks)',
    'Roof F (Barracks)',
    'Roor G (Ivy)',
    'Roof H (House)',
    'Outer Wall A (Stone)',
    'Outer Wall B (Factory)',
    'Outer Wall C (Metal, Red Rust)',
    'Outer Wall D (Barracks)',
    'Outer Wall E (Barracks)',
    'Outer Wall F (Factory)',
    'Outer Wall G (Ivy)',
    'Outer Wall H (House)',
    'Roof I (Barracks)',
    'Roof J (Brick)',
    'Roof K (Metal, Patina)',
    'Roof L (Chinese)',
    'Roof M (Blue Sheet)',
    'Roof N (Wood)',
    'Roof O (Brick)',
    'Roof P (Wood)',
    'Outer Wall I (Tile)',
    'Outer Wall J (Brick)',
    'Outer Wall K (Mortar)',
    'Outer Wall L (Chinese)',
    'Outer Wall M (Blue Sheet)',
    'Outer Wall N (Wood)',
    'Outer Wall O (Brick)',
    'Outer Wall P (Wood)',
  ],
  SF_Outside_A4: [
    'Wall A (Concrete)',
    'Wall B (Concrete, Dirty)',
    'Wall C (Block)',
    'Wall D (Apartment)',
    'Wall E (Apartment)',
    'Wall F (Metal)',
    'Wall G (Metal, Red Rust)',
    'Wall H (Metal, Patina)',
    'Wall A (Concrete)',
    'Wall B (Concrete, Dirty)',
    'Wall C (Block)',
    'Wall D (Apartment)',
    'Wall E (Apartment)',
    'Wall F (Metal)',
    'Wall G (Metal, Red Rust)',
    'Wall H (Metal, Patina)',
    'Wall I (Barracks)',
    'Wall J (Barracks)',
    'Wall K (Factory)',
    'Cliff A (Demonic Ground)',
    'Wall L (Factory)',
    'Wall M (Factory)',
    'Wall N (Building)',
    'Wall O (Brick)',
    'Wall I (Barracks)',
    'Wall J (Barracks)',
    'Wall K (Factory)',
    'Cliff A (Demonic Ground)',
    'Wall L (Factory)',
    'Wall M (Factory)',
    'Wall N (Building)',
    'Wall O (Brick)',
    'Wall P (Chinese)',
    'Wall Q (Wire Mesh)',
    'Wall R (Wire Mesh, Red Rust)',
    'Wall S (Wire Mesh, Patina)',
    'Wall T (Wood)',
    'Wall U (Wood, Dirty)',
    'Wall V (Building)',
    'Wall W (Building)',
    'Wall P (Chinese)',
    'Wall Q (Wire Mesh)',
    'Wall R (Wire Mesh, Red Rust)',
    'Wall S (Wire Mesh, Patina)',
    'Wall T (Wood)',
    'Wall U (Wood, Dirty)',
    'Wall V (Building)',
    'Wall W (Building)',
  ],
  SF_Outside_A5: [
    'Darkness',
    'Grid floor',
    'Metal Bridge (V, Left)',
    'Metal Bridge (V, Center)',
    'Metal Bridge (V, Right)',
    'Asphalt Bridge (H, Top)',
    'Metal Bridge (H, Center)',
    'Metal Bridge (H, Top)',
    'Transparent',
    'Grid floor',
    'Asphalt Bridge (V, Left)',
    'Asphalt Bridge (V, Center)',
    'Asphalt Bridge (V, Right)',
    'Asphalt Bridge (H, Bottom)',
    'Asphalt Bridge (H, Center)',
    'Metal Bridge (H, Bottom)',
    'Waste Land',
    'Metal Floor A (Factory)',
    'Concrete Floor',
    'Concrete Floor (Ruins)',
    'Hole',
    'Grid floor (Ruins)',
    'Asphalt Floor (Ruins)',
    'Metal Floor A (Factory, Ruins)',
    'Waste Land',
    'Metal Floor A (Factory)',
    'Concrete Floor',
    'Mecha Floor',
    'Stairs A (Asphalt, Left)',
    'Stairs A (Asphalt, Center)',
    'Stairs A (Asphalt, Right)',
    'Stairs A (Asphalt)',
    'Dirty Floor',
    'Dirty Floor (Ruins)',
    'Mecha Floor (Ruins) A',
    'Mecha Floor (Ruins) B',
    'Asphalt Floor (Dirty)',
    'Asphalt Floor (Dirty, Ruins)',
    'Wood Floor A',
    'Wood Floor A (Ruins)',
    'Bumpy Tile A',
    'Bumpy Tile B',
    'Bumpy Tile C',
    'Bumpy Tile C (Ruins)',
    'Stairs B (Metal, Left)',
    'Stairs B (Metal, Center)',
    'Stairs B (Metal, Right)',
    'Stairs B (Metal)',
    'Interior Floor A (Green Resin)',
    'Interior Floor B (Tile)',
    'Interior Floor B (Tile, Ruins)',
    'Interior Floor C (Decoration)',
    'Interior Floor D (Decoration)',
    'Interior Floor E (Decoration)',
    'Wood Floor B',
    'Wood Floor B (Ruins)',
    'Stairs C (Meadow, Left)',
    'Stairs C (Meadow, Center)',
    'Stairs C (Meadow, Right)',
    'Stairs C (Meadow)',
    'Stairs D (Wood, Left)',
    'Stairs D (Wood, Center)',
    'Stairs D (Wood, Right)',
    'Stairs D (Wood)',
    'Cobblestones A',
    'Cobblestones B',
    'Cobblestones C',
    'Cobblestones D',
    'Metal Floor B',
    'Metal Floor B (Rust, Ruins)',
    'Metal Floor C',
    'Metal Floor C (Rust, Ruins)',
    'Stairs E (Carpet, Left)',
    'Stairs E (Carpet, Center)',
    'Stairs E (Carpet, Right)',
    'Stairs E (Carpet)',
    'Stairs F (Desert, Left)',
    'Stairs F (Desert, Center)',
    'Stairs F (Desert, Right)',
    'Stairs F (Desert)',
    'Mark Floor A',
    'Mark Floor B',
    'Mark Floor C',
    'Mark Floor D',
    'Mark Floor E',
    'Mark Floor E (Ruins)',
    'Mark Floor F (Off)',
    'Mark Floor F',
    'Neon Floor',
    'Interior Floor F (Tile Carpet)',
    'Interior Floor F (Tile Carpet, Ruins)',
    'Ledge (Demonic Ground)',
    'Ledge (Demonic Ground)',
    'Ledge (Demonic Ground)',
    'Ledge (Demonic Ground)',
    'Ledge (Demonic Ground)',
    'Marble Floor',
    'Interior Floor G (Linoleum)',
    'Interior Floor G (Linoleum, Ruins)',
    'Ledge (Demonic Ground)',
    'Ledge (Demonic Ground)',
    'Ledge (Demonic Ground)',
    'Ledge (Demonic Ground)',
    'Ledge (Demonic Ground)',
    'Stairs G (Tile Carpet, Left)',
    'Stairs G (Tile Carpet, Center)',
    'Stairs G (Tile Carpet, Right)',
    'Stairs G (Tile Carpet)',
    'Cobblestones E',
    'Ledge (Demonic Ground)',
    'Ledge (Demonic Ground)',
    'Ledge (Demonic Ground)',
    'Stairs H (Linoleum, Left)',
    'Stairs H (Linoleum, Center)',
    'Stairs H (Linoleum, Right)',
    'Stairs H (Linoleum)',
    'Cobblestones F',
    'Cliff (Demonic Ground)',
    'Cliff (Demonic Ground)',
    'Cliff (Demonic Ground)',
    'Marble Floor (Ruins)',
    'Wood Floor C',
    'Wood Floor C (Ruins)',
    'Metal Floor D (Machine)',
    'Metal Floor D (Machine, Ruins)',
    'Cliff (Demonic Ground)',
    'Cliff (Demonic Ground)',
    'Cliff (Demonic Ground)',
  ],
  SF_Outside_B: [
    'Transparent',
    'Neon Shop Sign (Weapon)',
    'Neon Shop Sign (Armor)',
    'Neon Shop Sign (Item)',
    'Neon Shop Sign (Pharmacy)',
    'Neon Shop Sign (Cafe)',
    'Neon Shop Sign (Inn)',
    'Neon Shop Sign (Market)',
    'Metal Shop Sign (Weapon)',
    'Metal Shop Sign (Armor)',
    'Metal Shop Sign (Item)',
    'Metal Shop Sign (Pharmacy)',
    'Metal Shop Sign (Cafe)',
    'Metal Shop Sign (Inn)',
    'Metal Shop Sign (Firearm)',
    'Metal Shop Sign (Blank)',
    'Asphalt Bridge (V)',
    'Asphalt Bridge (H)',
    'Stone Bridge (V)',
    'Stone Bridge (H)',
    'Metal Bridge A (V)',
    'Metal Bridge A (H)',
    'Metal Bridge B (V)',
    'Metal Bridge B (H)',
    'Bridge Spar A (Asphalt, Center A)',
    'Bridge Spar A (Asphalt, Left)',
    'Bridge Spar A (Asphalt, Center B)',
    'Bridge Spar A (Asphalt, Right)',
    'Bridge Spar B (Metal, Center A)',
    'Bridge Spar B (Metal, Left)',
    'Bridge Spar B (Metal, Center B)',
    'Bridge Spar B (Metal, Right)',
    'White Line',
    'White Line',
    'White Line',
    'White Line',
    'White Line',
    'Red & Black Line',
    'Red & Black Line',
    'Red & Black Line',
    'White Line',
    'Traffic Lights (Car)',
    'Traffic Lights (Pedestrian)',
    'Entrance A',
    'White Line (Crosswalk)',
    'Red & Black Line',
    'Traffic Cone',
    'Red & Black Line',
    'White Line',
    'Traffic Lights (Car)',
    'Traffic Lights (Pedestrian)',
    'Entrance B',
    'White Line',
    'Red & Black Line',
    'Red & Black Line',
    'Red & Black Line',
    'Window A',
    'Window B',
    'Window C',
    'Window D',
    'Window E',
    'Window F',
    'Window G',
    'Window H',
    'Midsize Window A',
    'Midsize Window B',
    'Midsize Window C',
    'Midsize Window D',
    'Midsize Window E',
    'Midsize Window F',
    'Midsize Window G',
    'Midsize Window H',
    'Midsize Window A',
    'Midsize Window B',
    'Midsize Window C',
    'Midsize Window D',
    'Midsize Window E',
    'Midsize Window F',
    'Midsize Window G',
    'Midsize Window H',
    'Neon Shop Sign (V)',
    'Neon Shop Sign (V)',
    'Neon Shop Sign (V)',
    'Neon Shop Sign (H)',
    'Neon Shop Sign (H)',
    'Street Light A',
    'Street Light B',
    'Stained Glass Window',
    'Neon Shop Sign (V)',
    'Neon Shop Sign (V)',
    'Neon Shop Sign (V)',
    'Neon Shop Sign (H)',
    'Neon Shop Sign (H)',
    'Street Light A',
    'Street Light B',
    'Stained Glass Window',
    'Neon Shop Sign (V)',
    'Neon Shop Sign (V)',
    'Neon Shop Sign (V)',
    'Neon Shop Sign (H)',
    'Neon Shop Sign (H)',
    'Stacked Crates',
    'Shipping Container',
    'Stacked Cardboard',
    'Chimney A',
    'Chimney B',
    'Chimney C',
    'Exhaust Port Wall',
    'Roof Window',
    'Stacked Crates',
    'Shipping Container',
    'Stacked Cardboard',
    'Wall Poster',
    'Signboard A',
    'Signboard B',
    'Digital Signage A',
    'Digital Signage C',
    'Neon Shop Sign (CASINO)',
    'Neon Shop Sign (CASINO)',
    'Small Crane',
    'Poster',
    'Signboard C',
    'Digital Signage B',
    'Digital Signage B',
    'Digital Signage C',
    'Iron Materials',
    'Helmet',
    'Small Crane',
    'Crate',
    'Shipping Container',
    'Cardboard Box',
    'Barrel',
    'Oil Drum',
    'Garbage Can',
    'Sorted Waste Bins',
    'Sorted Waste Bins',
    'Plant A',
    'Plant B',
    'Plant C',
    'Vending Machine',
    'ATM',
    'Tree',
    'Roadside Tree',
    'Utility Pole',
    'Plant A',
    'Plant B',
    'Plant C',
    'Vending Machine',
    'ATM',
    'Tree',
    'Avenue Tree',
    'Utility Pole',
    'Public Phone',
    'Machine Device',
    'Planter (Plant)',
    'Planter (Potted Plant)',
    'Potted Plant',
    'Tree (Loop)',
    'Tombstone (Cross)',
    'Tombstone (Plaque)',
    'Neon Tube',
    'Neon Tube',
    'Machine A',
    'Machine B',
    'Machine C',
    'Barricade (No Entry)',
    'Bar (No Entry)',
    'Bar (No Entry)',
    'Neon Tube',
    'Neon Tube',
    'Outdoor Air Intake Unit',
    'Waste',
    'Scrap Metal',
    'Fissures A',
    'Fissures B',
    'Fissures C',
    'Neon Tube',
    'Neon Tube',
    'Air Vent A',
    'Air Vent B',
    'Shutter',
    'Fissures A',
    'Fissures B',
    'Fissures C',
    'Drain',
    'Guardrail',
    'Timetable',
    'Piled Up Tires',
    'Small Fuel Tank',
    'Car (Red)',
    'Car (Red)',
    'Manhole',
    'Bus',
    'Bus',
    'Truck',
    'Truck',
    'Wrecked Car',
    'Car (Black)',
    'Car (Black)',
    'Vent',
    'Bus',
    'Bus',
    'Truck',
    'Truck',
    'Wrecked Car',
    'Car (Blue)',
    'Car (Blue)',
    'Oil Drum (Leak)',
    'Food Stalls',
    'Food Stalls',
    'Food Stalls',
    'Stall Goods A',
    'Stairs A (Up)',
    'Stairs B (Up)',
    'Stairs C (Down)',
    'Stairs D (Down)',
    'Food Stalls',
    'Food Stalls',
    'Food Stalls',
    'Stall Goods B',
    'Stairs C (Up)',
    'Stairs D (Up)',
    'Stairs A (Down)',
    'Stairs B (Down)',
    'Food Stalls',
    'Food Stalls',
    'Food Stalls',
    'Stall Goods C',
    'Metal Ladder',
    'Metal Stairs',
    'Rope',
    'Net',
    'Junk Stalls',
    'Junk Stalls',
    'Junk Stalls',
    'Stall Goods D',
    'Metal Ladder',
    'Metal Stairs',
    'Rope',
    'Net',
    'Junk Stalls',
    'Junk Stalls',
    'Junk Stalls',
    'Stall Goods E',
    'Metal Ladder',
    'Metal Stairs',
    'Rope',
    'Net',
    'Junk Stalls',
    'Junk Stalls',
    'Junk Stalls',
    'Stall Goods F',
    'Hole A (Metal Ladder)',
    'Hole B (Metal Stairs)',
    'Hole C (Rope)',
    'Hole',
  ],
  SF_Outside_C: [
    'Fountain A',
    'Fountain A',
    'Fountain B',
    'Fountain B',
    'Slide',
    'Slide',
    'Exercise Bar',
    'Drinking Fountain',
    'Fountain A',
    'Fountain A',
    'Fountain B',
    'Fountain B',
    'Slide',
    'Slide',
    'Water Well Pump',
    'Garbage Dumpster',
    'Fountain C',
    'Fountain C',
    'Fountain C',
    'Bench A',
    'Bench A',
    'Swing',
    'Shop Canopy',
    'Barbed Wire',
    'Fountain C',
    'Fountain C',
    'Fountain C',
    'Bench B',
    'Bench B',
    'Swing',
    'Shop Canopy',
    'Barbed Wire',
    'Grass A',
    'Grass B',
    'Hole',
    'Small Stones',
    'Flower Bed',
    'Flower Bed',
    'Flower Bed',
    'Barbed Wire',
    'Flower',
    'Cage',
    'Cage',
    'Graffiti',
    'Graffiti',
    'Barbed Wire',
    'Barbed Wire',
    'Barbed Wire',
    'Demon Statue',
    'Goddess Statue',
    'Metal Fence',
    'Metal Fence',
    'Metal Fence',
    'Gutter',
    'Gutter',
    'Gutter',
    'Demon Statue',
    'Goddess Statue',
    'Metal Fence',
    'Warning Plate',
    'Metal Fence',
    'Gutter',
    'Postal Box',
    'Gutter',
    'Soldier Statue',
    'Warning Plate (Biohazard Mark)',
    'Metal Fence',
    'Metal Fence',
    'Metal Fence',
    'Gutter',
    'Gutter',
    'Gutter',
    'Soldier Statue',
    'Pillar A (Asphalt)',
    'Pillar B (Metal)',
    'Pillar C (Machine)',
    'Pillar D (Decoration)',
    'Pillar E (Metal)',
    'Pillar F (Brick)',
    'Food Waste',
    'Warning Plate',
    'Pillar A (Asphalt)',
    'Pillar B (Metal)',
    'Pillar C (Machine)',
    'Pillar D (Decoration)',
    'Pillar E (Metal)',
    'Pillar F (Brick)',
    'Mysterious Liquid',
    'Warning Plate',
    'Broken Pillar A (Asphalt)',
    'Broken Pillar B (Metal)',
    'Broken Pillar C (Machine)',
    'Broken Pillar D (Decoration)',
    'Broken Pillar E (Metal)',
    'Broken Pillar F (Brick)',
    'Fire Hydrant',
    'Monument A',
    'Monument B',
    'Huge Stele',
    'Huge Stele',
    'Huge Stele',
    'Huge Iron Monument',
    'Huge Iron Monument',
    'Huge Iron Monument',
    'Monument A',
    'Monument B',
    'Huge Stele',
    'Huge Stele',
    'Huge Stele',
    'Huge Iron Monument',
    'Huge Iron Monument',
    'Huge Iron Monument',
    'Monument C',
    'Monument D',
    'Sphere Machinery',
    'Sphere Machinery',
    'Sphere Machinery',
    'Large Machine',
    'Large Machine',
    'Large Machine',
    'Monument C',
    'Control Panel',
    'Sphere Machinery',
    'Sphere Machinery',
    'Sphere Machinery',
    'Large Machine',
    'Large Machine',
    'Large Machine',
    'Wall A',
    'Wall A',
    'Wall A',
    'Decorative Pillar A',
    'Arch A',
    'Arch A',
    'Arch A',
    'Decorative Pillar B',
    'Wall A',
    'Wall A',
    'Wall A',
    'Decorative Pillar A',
    'Arch A',
    'Arch A',
    'Arch A',
    'Decorative Pillar B',
    'Wall A',
    'Wall A',
    'Wall A',
    'Decorative Pillar A',
    'Arch A',
    'Arch A',
    'Arch A',
    'Decorative Pillar B',
    'Wall B (Topside)',
    'Wall B (Topside)',
    'Wall B (Topside)',
    'Spire',
    'Clock Tower',
    'Clock Tower',
    'Clock Tower',
    'Wall A Ceiling',
    'Wall B (Topside)',
    'Wall B (Topside)',
    'Wall B (Topside)',
    'Spire',
    'Clock Tower',
    'Clock Tower',
    'Clock Tower',
    'Decorative Pillar A (Front)',
    'Wall B (Topside)',
    'Wall B (Topside)',
    'Wall B (Topside)',
    'Spire',
    'Clock Tower',
    'Clock Tower',
    'Clock Tower',
    'Decorative Pillar B (Front)',
    'Wall B',
    'Wall B',
    'Wall B',
    'Spire',
    'Arch B',
    'Arch B',
    'Arch B',
    'Iron Fence B',
    'Wall B',
    'Wall B',
    'Wall B',
    'Spire',
    'Arch B',
    'Arch B',
    'Arch B',
    'Gate',
    'Wall B',
    'Wall B',
    'Wall B',
    'Spire',
    'Arch B',
    'Arch B',
    'Arch B',
    'Gate',
    'Rooftop Railing',
    'Rooftop Railing',
    'Rooftop Railing',
    'Iron Fence A',
    'Tank',
    'Tank',
    'Helicopter',
    'Helicopter',
    'Rooftop Railing',
    'Round Clock',
    'Rooftop Railing',
    'Iron Fence A',
    'Tank',
    'Tank',
    'Helicopter',
    'Helicopter',
    'Rooftop Railing',
    'Rooftop Railing',
    'Rooftop Railing',
    'Iron Fence A',
    'Rooftop Billboard B',
    'Rooftop Billboard B',
    'Food Cart',
    'Food Cart',
    'Convenience Store',
    'Convenience Store',
    'Convenience Store',
    'Steel Tower',
    'Rooftop Billboard A',
    'Roof',
    'Roof',
    'Roof',
    'Convenience Store',
    'Convenience Store',
    'Convenience Store',
    'Steel Tower',
    'Water Storage Tank',
    'Roof',
    'Roof',
    'Roof',
    'Bus Waiting Area',
    'Bus Waiting Area',
    'Station Kiosk',
    'Steel Tower',
    'Water Storage Tank',
    'Roof',
    'Roof',
    'Roof',
    'Bus Waiting Area',
    'Bus Waiting Area',
    'Station Kiosk',
    'Roof Detail',
    'Roof',
    'Roof',
    'Roof',
    'Roof',
  ],
  SF_Inside_A4: [
    'Wall A (Concrete)',
    'Wall B (Concrete)',
    'Wall C (House)',
    'Wall D (Metal)',
    'Wall E (Metal, Red Rust)',
    'Wall F (Metal, Patina)',
    'Wall G (Barracks)',
    'Wall H (Chinese)',
    'Wall A (Concrete)',
    'Wall B (Concrete)',
    'Wall C (House)',
    'Wall D (Metal)',
    'Wall E (Metal, Red Rust)',
    'Wall F (Tent, Camouflage)',
    'Wall G (Barracks)',
    'Wall H (Chinese)',
    'Wall I (Factory)',
    'Wall J (Factory)',
    'Interior Wall A (Pattern)',
    'Interior Wall B (Pattern)',
    'Interior Wall C (Pattern)',
    'Interior Wall D (Pattern)',
    'Interior Wall E (Pattern)',
    'Wall K (Brick)',
    'Wall I (Factory)',
    'Wall J (Factory)',
    'Interior Wall A (Pattern)',
    'Interior Wall B (Pattern)',
    'Interior Wall C (Pattern)',
    'Interior Wall D (Pattern)',
    'Interior Wall E (Pattern)',
    'Wall K (Brick)',
    'Wall L (Wood)',
    'Wall M (House)',
    'Wall N (Building)',
    'Wall O (Other Dimension)',
    'Wall P (Neon)',
    'Wall Q (Wire Mesh)',
    'Wall R (Wire Mesh, Red Rust)',
    'Wall S (Wire Mesh, Patina)',
    'Wall L (Wood)',
    'Wall M (House)',
    'Wall N (Building)',
    'Wall O (Other Dimension)',
    'Wall P (Neon)',
    'Wall Q (Wire Mesh)',
    'Wall R (Wire Mesh, Red Rust)',
    'Wall S (Wire Mesh, Patina)',
  ],
  SF_Inside_B: [
    'Transparent',
    'Stairs A (Up)',
    'Stairs B (Up)',
    'Stairs C (Up)',
    'Stairs D (Up)',
    'Wood Ladder',
    'Metal Stairs',
    'Crane Rope',
    'Hole',
    'Stairs A (Down)',
    'Stairs B (Down)',
    'Stairs C (Down)',
    'Stairs D (Down)',
    'Wood Ladder',
    'Metal Stairs',
    'Crane Rope',
    'Midsize Window A',
    'Midsize Window B',
    'Large Window A',
    'Midsize Window C',
    'Large Window B',
    'Wood Ladder',
    'Metal Stairs',
    'Crane Rope',
    'Midsize Window A',
    'Midsize Window B',
    'Large Window A',
    'Midsize Window C',
    'Large Window B',
    'Hole A (Wood Ladder)',
    'Hole B (Metal Stairs)',
    'Hole C (Crane Rope)',
    'Asphalt Bridge (V)',
    'Asphalt Bridge (H)',
    'Stone Bridge (V)',
    'Stone Bridge (H)',
    'Metal Bridge A (V)',
    'Metal Bridge A (H)',
    'Metal Bridge B (V)',
    'Metal Bridge B (H)',
    'Bridge Spar A (Asphalt, Center A)',
    'Bridge Spar A (Asphalt, Left)',
    'Bridge Spar A (Asphalt, Center B)',
    'Bridge Spar A (Asphalt, Right)',
    'Bridge Spar B (Metal, Center A)',
    'Bridge Spar B (Metal, Left)',
    'Bridge Spar B (Metal, Center B)',
    'Bridge Spar B (Metal, Right)',
    'Metal Fence',
    'Metal Fence',
    'Metal Fence',
    'Warning Plate A',
    'Connecting Bridge (Metal)',
    'Connecting Bridge (Metal)',
    'Connecting Bridge (Metal)',
    'Connecting Bridge (Metal, Stairs)',
    'Metal Fence',
    'Warning Plate B',
    'Metal Fence',
    'Warning Plate C',
    'Connecting Bridge (Metal)',
    'Connecting Bridge (Metal)',
    'Connecting Bridge (Metal)',
    'Connecting Bridge (Metal, Stairs)',
    'Metal Fence',
    'Metal Fence',
    'Metal Fence',
    'Warning Plate (Biohazard Mark)',
    'Connecting Bridge (Metal)',
    'Connecting Bridge (Metal)',
    'Connecting Bridge (Metal)',
    'Podium (H)',
    'Pillar A (Asphalt)',
    'Pillar B (Metal)',
    'Pillar C (Display)',
    'Pillar D (Decoration)',
    'Pillar E (Metal)',
    'Pillar F (Brick)',
    'Large Window C',
    'Podium (H)',
    'Pillar A (Asphalt)',
    'Pillar B (Metal)',
    'Pillar C (Display)',
    'Pillar D (Decoration)',
    'Pillar E (Metal)',
    'Pillar F (Brick)',
    'Large Window C',
    'Podium (V)',
    'Broken Pillar A (Asphalt)',
    'Broken Pillar B (Metal)',
    'Broken Pillar C (Display)',
    'Broken Pillar D (Decoration)',
    'Broken Pillar E (Metal)',
    'Broken Pillar F (Brick)',
    'Barricade (No Entry)',
    'Podium (V)',
    'Girder A (Asphalt, Left)',
    'Girder A (Asphalt, Center)',
    'Girder A (Asphalt, Right)',
    'Girder C (Decoration, Left)',
    'Girder C (Decoration, Center)',
    'Girder C (Decoration, Right)',
    'Bar (No Entry)',
    'Bar (No Entry)',
    'Girder B (Metal, Left)',
    'Girder B (Metal, Center)',
    'Girder B (Metal, Right)',
    'Rubble A (Asphalt)',
    'Rubble B (Metal)',
    'Fissures A',
    'Fissures B',
    'Fissures C',
    'Jail Bars',
    'Laser Barrier',
    'Wheelchair (Left)',
    'Wheelchair (Right)',
    'Pipe Frame Bed (Ruins)',
    'Fissures A',
    'Fissures B',
    'Fissures C',
    'Jail Bars',
    'Laser Barrier',
    'Wheelchair (Bottom)',
    'Wheelchair (Fallen)',
    'Pipe Frame Bed (Ruins)',
    'Lab Equipment',
    'School Desk (V)',
    'School Desk (H)',
    'TV',
    'Computer',
    'Laptop',
    'Printer',
    'Telephone',
    'Intercom (Hanging)',
    'Tablet Device',
    'Table Clock',
    'Gas Stove',
    'Kitchen Counter',
    'Sink',
    'Exhaust Fan',
    'Air Conditioner',
    'Wastebasket',
    'Book Stand',
    'Document',
    'School Chair (Bottom)',
    'School Chair (Top)',
    'School Chair (Right)',
    'School Chair (Left)',
    'Sofa (Right)',
    'Sofa (Left)',
    'Sofa (Down)',
    'Sofa (Up)',
    'Office Chair (Bottom)',
    'Office Chair (Top)',
    'Office Chair (Right)',
    'Office Chair (Left)',
    'Sofa (Right)',
    'Sofa (Left)',
    'Sofa (Top)',
    'Sofa (Top)',
    'Washing Machine',
    'Western Style Toilet',
    'Urinal',
    'Bathroom Sink',
    'Bathtub (V)',
    'Bathtub (H)',
    'Bathtub (H)',
    'Glass Table (V)',
    'Washing Machine',
    'Western Style Toilet',
    'Urinal',
    'Wash Basin',
    'Bathtub (V)',
    'Glass Table (H)',
    'Glass Table (H)',
    'Glass Table (V)',
    'Refrigerator',
    'Bookshelf A',
    'Chest of Drawers A',
    'Miscellaneous Item Shelf',
    'Locker A',
    'Document Shelf',
    'Medicine Shelf',
    'Locker B (School)',
    'Refrigerator',
    'Bookshelf A',
    'Chest of Drawers A',
    'Miscellaneous Item Shelf',
    'Locker A',
    'Document Shelf',
    'Medicine Shelf',
    'Locker B (School)',
    'Display Shelf A',
    'Display Shelf B',
    'Convenience Store Shelf A',
    'Convenience Store Shelf B',
    'Document Shelf (Ruins)',
    'Chest of Drawers B (Decoration)',
    'Shelf A (Decoration)',
    'Bookshelf B (Decoration)',
    'Display Shelf A',
    'Display Shelf B',
    'Convenience Store Shelf A',
    'Convenience Store Shelf B',
    'Document Shelf (Ruins)',
    'Chest of Drawers B (Decoration)',
    'Shelf A (Decoration)',
    'Bookshelf B (Decoration)',
    'Stacked Crates',
    'Shipping Container',
    'Stacked Cardboard Boxes',
    'Vending Machine',
    'ATM',
    'Steel Shelf',
    'Operating Table',
    'Hospital Bed',
    'Stacked Crates',
    'Shipping Container',
    'Stacked Cardboard Boxes',
    'Vending Machine',
    'ATM',
    'Steel Shelf',
    'Operating Table',
    'Hospital Bed',
    'Bed',
    'Mattress',
    'Large Bed',
    'Large Bed',
    'Pipe Frame Bed',
    'Slot Machine',
    'Poker Table',
    'Poker Table',
    'Bed',
    'Mattress',
    'Large Bed',
    'Large Bed',
    'Pipe Frame Bed',
    'Slot Machine',
    'Poker Table',
    'Poker Table',
    'Chest A (Wood)',
    'Chest B (Metal)',
    'Chest C (Decoration)',
    'Large Desk A',
    'Large Desk A',
    'Roulette Table',
    'Roulette Table',
    'Roulette Table',
    'Side Desk A (Wood)',
    'Side Desk B (Metal)',
    'Desk',
    'Large Desk B',
    'Large Desk B',
    'Roulette Table',
    'Roulette Table',
    'Roulette Table',
  ],
  SF_Inside_C: [
    'Black Board',
    'Black Board',
    'Black Board',
    'White Board',
    'White Board',
    'White Board',
    'Partition A',
    'Partition B',
    'Black Board',
    'Black Board',
    'Black Board',
    'White Board',
    'White Board',
    'White Board',
    'Partition A',
    'Partition B',
    'Stool',
    'Skeleton Model',
    'Biological Specimen',
    'Potted Plant',
    'Armchair',
    'Insect Specimen',
    'Restroom Mark (Men)',
    'Restroom Mark (Women)',
    'Wall Speaker',
    'Skeleton Model ',
    'Biological Specimen',
    'Fire Extinguisher',
    'Armchair',
    'Room Plate',
    'EXIT Sign',
    'Vent',
    'Painting A',
    'Painting B',
    'Vision Test Chart',
    'Plaster Bust',
    'Calendar',
    'Plant A',
    'Plant B',
    'Plant C',
    'Painting C',
    'Painting D',
    'Anatomical Chart',
    'Canvas',
    'Bulletin Board',
    'Plant A',
    'Plant B',
    'Plant C',
    'Plumbing',
    'Plumbing',
    'Valve',
    'Machine A',
    'Machine B',
    'Machine C',
    'Air Vent A',
    'Air Vent B',
    'Plumbing',
    'Plumbing',
    'Plumbing',
    'Neon Tube',
    'Neon Tube',
    'Neon Tube',
    'Fan',
    'Fluorescent Light',
    'Plumbing',
    'Plumbing',
    'Plumbing',
    'Neon Tube',
    'Neon Tube',
    'Neon Tube',
    'Outdoor Air Intake Unit',
    'Shutter',
    'Plumbing',
    'Plumbing',
    'Plumbing',
    'Control Panel A',
    'Control Panel B',
    'Control Panel C',
    'Pipe (H)',
    'Pipe (V)',
    'Line A',
    'Line B',
    'Road Closed',
    'Waste',
    'Scrap Metal',
    'Mysterious Liquid',
    'Scattered Papers',
    'Pipe (V)',
    'Belt Conveyor (V)',
    'Belt Conveyor (H)',
    'Belt Conveyor (H)',
    'Belt Conveyor (H)',
    'Duct',
    'Mechanical Device',
    'Pile of Rubble',
    'Pile of Rubble',
    'Belt Conveyor (V)',
    'Robot Arm',
    'Server Machine',
    'Meters',
    'Duct',
    'Mechanical Device',
    'Pile of Rubble',
    'Pile of Rubble',
    'Belt Conveyor (V)',
    'Robot Arm',
    'Server Machine',
    'Meters',
    'Duct',
    'Drain',
    'Graffiti',
    'Graffiti',
    'Monitor A',
    'Monitor B',
    'Large Monitor',
    'Large Monitor',
    'IV Stand',
    'ECG Monitor',
    'Sewing Mannequin',
    'Rubble',
    'Operation Board A',
    'Operation Board B',
    'Operation Board C',
    'Operation Board D',
    'IV Stand',
    'ECG Monitor',
    'Sewing Mannequin',
    'Broken Machine',
    'Stairs',
    'Stairs',
    'Stairs',
    'Cage',
    'Cage',
    'Handrail',
    'Handrail',
    'Handrail',
    'Stairs',
    'Stairs',
    'Stairs',
    'Curtains A',
    'Curtains B',
    'Curtains C',
    'Curtains D',
    'Handrail',
    'Stairs',
    'Stairs',
    'Stairs',
    'Curtains A',
    'Curtains B',
    'Curtains C',
    'Curtains D',
    'Emergency Alarm',
    'Spider Web',
    'Mirror',
    'Vase',
    'Piano',
    'Piano',
    'Piano',
    'Stained Glass',
    'Decorative Pillar',
    'Dripping',
    'Mirror',
    'Lamp',
    'Piano',
    'Piano',
    'Piano',
    'Stained Glass',
    'Decorative Pillar',
    'Picture Frame',
    'Side Table',
    'Altar',
    'Fireplace',
    'Fireplace',
    'Fireplace',
    'Stuffed Doll A',
    'Decorative Pillar',
    'Book A',
    'Book B',
    'Glass Pieces',
    'Fireplace',
    'Fireplace',
    'Fireplace',
    'Doll',
    'Stuffed Doll B',
    'Beer Mug',
    'Wine & Glass',
    'Noodle Dish',
    'Bread',
    'Banister A (V)',
    'Banister A (V)',
    'Banister B (V)',
    'Banister B (V)',
    'Meat Dish',
    'Roast Chicken',
    'Cake',
    'Fruit Bowl',
    'Banister A (V)',
    'Banister A (V)',
    'Banister B (V)',
    'Banister B (V)',
    'Plate A',
    'Teapot & Cup',
    'Ration',
    'Plate B',
    'Banister A (V)',
    'Banister A (V)',
    'Banister B (V)',
    'Banister B (V)',
    'Demon Statue',
    'Goddess Statue',
    'Soldier Statue',
    'Wall Clock',
    'Banister A (H)',
    'Banister A (H)',
    'Banister A (H)',
    'Banister A (H)',
    'Demon Statue',
    'Goddess Statue',
    'Soldier Statue',
    'Wall Clock',
    'Banister B (H)',
    'Banister B (H)',
    'Banister B (H)',
    'Banister B (H)',
    'Monument A',
    'Monument B',
    'Huge Stele',
    'Huge Stele',
    'Huge Stele',
    'Huge Display',
    'Huge Display',
    'Huge Display',
    'Monument A',
    'Monument B',
    'Huge Stele',
    'Huge Stele',
    'Huge Stele',
    'Huge Display',
    'Huge Display',
    'Huge Display',
    'Monument C',
    'Monument D',
    'Sphere Machinery',
    'Sphere Machinery',
    'Sphere Machinery',
    'Large Machine',
    'Large Machine',
    'Large Machine',
    'Monument C',
    'Control Panel',
    'Sphere Machinery',
    'Sphere Machinery',
    'Sphere Machinery',
    'Large Machine',
    'Large Machine',
    'Large Machine',
  ],
};
